### ISSUE TITLE
airshipctl base commands (example from Jira)

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#1]
Both the CLI and the UI will need to be able to leverage a standard k8ssecurity context for interacting with remote sites. It should also understandAirship site contexts so that it can be pointed at a local document set andwork with that during subsequent commands without needingto be fed the same document set with every command similar to interactingwith the same Kubernetes cluster throughout a kubectl session.

The initial proposed list of commands that will be implemented is defined below:

Every command will support :

*GENERIC OPTIONS*

-----------------------------------------------------------------+

NAME               

USAGE                             

=================================================================+

help                

Help for the appropriate command          

it also lists available plugins           

-----------------------------------------------------------------+

version             

Version of airshipctl.                    

-----------------------------------------------------------------+

**Comment by jezogwza** [comment]
This was achieved already with merged patchset https://review.opendev.org/#/c/689859/
