### ISSUE TITLE
Implement CLI level flag and argument validation

### ISSUE THREAD

**Issue by ianpittwood** [airshipit/airshipctl#10]
**Problem description (if applicable)**
Currently, most argument/flag validation occurs at the package level or is non-existent. This can lead to unnecessary code running up to argument/flag validation.

**Proposed change**
To avoid running unnecessary code and make the CLI as usable as possible, we should consider implementing validation at our CLI level. Many pre-built validators are available in the [Cobra CLI](https://github.com/spf13/cobra/blob/master/README.md) package for both arguments and flags. For additional validation for parameters such as URLs or file paths, we can consider building custom shared validation functions callable from the `Args` section of each targeted command.

**Potential impacts**
CLI validation could replace package level implementations of validation. However if airshipctl is to be used as both a CLI application and a library, validation may need to exist at both levels which potentially adds duplicated code.

**Comment by ian-howell** [comment]
Unfortunately, much of the validation that airshipctl does is not currently implemented in Cobra or Pflag. Some of this validation will probably require upstream work.

See for example this issue concerning [falg value restrictions](https://github.com/spf13/pflag/issues/236)

**Comment by ianpittwood** [comment]
I think we can implement most of this using `PreRunE` or `Args` if Cobra and Pflag aren't caught up to that point yet.

**Comment by alexander-hughes** [comment]
Work is being tracked in [Gerrit](https://review.opendev.org/#/c/706976/)
