### ISSUE TITLE
Update network-config example for isogen

### ISSUE THREAD

**Issue by jingvar** [airshipit/airshipctl#108]
**Problem description (if applicable)**
Netwok config must be in JSON format

**Proposed change**
Convert debian-isogen/examples/network-config in cloud-init network_data.json format

**Potential impacts**
None

**Comment by jezogwza** [comment]
We are questioning whether this is the right place to do this. IF the Network Config has to be JSON, will loose the ability to use kustomize to normalized network data for hosts.

**Comment by jingvar** [comment]
Link: https://review.opendev.org/712667/
Subject: Example network-config network_data.json format
Authored By: Nikolay Fedorov (nfedorov@mirantis.com)
