### ISSUE TITLE
Print sub-command help menu when passing -h or --help to a sub cmd

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#114]
**Describe the bug**
Passing `-h` or `--help` at the end of a command that uses a sub-command does not print the help menu if arguments are not provided.

**Steps To Reproduce**
```
root@annie:~/airshipctl# ./bin/airshipctl config set-context --manifest -h
you must specify a non-empty context name
root@annie:~/airshipctl# ./bin/airshipctl config set-context --manifest --help
you must specify a non-empty context name
root@annie:~/airshipctl# ./bin/airshipctl config set-context default --manifest --help
context “default” modified.
```

**Expected behavior**
The help menu for the sub-command is displayed.

**Comment by sirajyasin** [comment]
I can look into this bug

**Comment by sirajyasin** [comment]
Syntax:
./airshipctl$ ./airshipctl config set-context  -h   => shows help message
./airshipctl config set-context  --manifest=default -h  => shows help message
**./airshipctl config set-context  --manifest -h  => no help message**
./airshipctl config set-context  --current --manifest=default -h  => shows help message

In the third scenario which is reported as bug, the -h is treated as value to --manifest. So it does not show usage ( help message )

Available options to set context attributes:
1. /airshipctl$ ./airshipctl config set-context  default --manifest=default
Context "default" modified.
2. ./airshipctl config set-context  --current --manifest=default
Context "default" modified.

Please suggest if this still considered as bug.

**Comment by sirajyasin** [comment]
It is applicable for all commands.
./airshipctl config get-cluster --cluster-type --help  => shows cluster details and not the help

because I assume  --help is treated as value for the --cluster-type. But i am wondering how it still returns a cluster with target type. This might be an issue.

**Comment by drewwalters96** [comment]
Hey @sirajyasin. This item is still in triage, so we haven't quite determined that yet. This item will be reviewed Wednesday during the [Airship Flightplan call](https://wiki.openstack.org/wiki/Airship#AIRSHIP_Flight_Plan_-_Community_Management_Meetings). 

In the meantime, did you discover if it was possible to prevent passing flags (i.e. -h) to other flags using Cobra? That would help speed up the triage of this story.

**Comment by ian-howell** [comment]
I think this issue may need to be modified a bit. The original reporter of the issue was trying to get documentation on the flags passed to the `config set-manifest` subcommand by passing the desired flag `--manifest` and the `--help` flag. As @sirajyasin has pointed out, the `--help` flag can only be used for a `cobra.Command`, and not a `pflag.Flag`

This issue could be alleviated by providing better documentation when a user runs `airshipctl config set-manifest --help`, but without upstream changes to `cobra` and `pflag`, there's not much we can do.

**Comment by jezogwza** [comment]
Will close this since its not really a bug but misuse of the aitshipctl because of lack of documentation or information.

Opened #128 instead
