### ISSUE TITLE
`redfish.RedfishConfigError` does not implement the error interface

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#12]
**Problem description (if applicable)**
The current implementation of `redfish.RedfishConfigError` does not have an `Error` method, and therefore doesn't implement the `error` interface. This can be annoying for a user trying to type switch on the error

**Proposed change**
Implement the `Error` method on `redfish.RedfishConfigError`. This error could also benefit from a renaming to more closely match the other errors in `airshipctl`

**Comment by alexander-hughes** [comment]
@ian-howell can you provide more information on this issue?

**Comment by ian-howell** [comment]
Sure. Go has a builtin interface called [`error`](https://tour.golang.org/methods/19). Basically, any struct that has the following method:

```
func (s myStruct) Error() string
```

implements the `error` interface, and can be used like a builtin error. That means we can do useful things such as check what kind of error we've received using [`errors.Is`](https://golang.org/pkg/errors/#Is) and [`errors.As`](https://golang.org/pkg/errors/#As).

This issue simply requires adding that method to the redfish error, and as mentioned, renaming it to match the conventions of other errors in `airshipctl` (e.g. `ErrMissingConfig`, `ErrNotImplemented`, etc)

**Comment by alexander-hughes** [comment]
Tracking work in [Gerrit](https://review.opendev.org/#/c/707203/)
