### ISSUE TITLE
Enhanced airshipctl deep help documentation

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#128]
**Problem description (if applicable)**
Currently there is no way of providing help information for all flags and variations of airshipctl command. 

**Proposed change**
We need to define the mechanism through which we would provide that information, and then create individual issues to update airshipctl accordingly.

**Potential impacts**
All airshipctl command might need to be updated.

**Comment by sirajyasin** [comment]
I can look into this issue and come up with an approach of expanding the help for airshipctl.

**Comment by sirajyasin** [comment]
**My initial analysis to improve help for aishipctl:**

1. Add more examples to help description wherever applicable 
	**example**: 
		1.a _airshipctl cluster initinfra_  => no example for flags
2. Update examples with more meaningful placeholders and values.
	**example**:
		2.a _airshipctl config get-credentials NAME [flags]_ 
				=> NAME => can be USERNMAE ?, in general can it be relevant to the command like 'CLUSTER_NAME', 'CONTEXT_NAME'
				=> _airshipctl config get-credentials e2e_ => e2e is cluster, it should be user 'admin'
				=> _airshipctl config set-context e2e_ => e2e is cluster, it should be context 'default'
		2.b airshipctl config set-credentials cluster-admin --username=~/.kube/admin.key
				=> --username has a value of key file		
3. Add more validations to the command values(pFlags):
	**example**:
		3.a _airshipctl config set-credentials cluster-admin --client-key=~/.kube/admin.key_
				=> success even if key path does not exists

Please suggest if we can do these cleanups/improvements as part of this issue

**Comment by sirajyasin** [comment]
All the above mentioned issues are fixed in this commit.
https://review.opendev.org/#/c/720301/

A separate help command to get help on any given command/subcommand is also available now.
So this issue can be marked closed

**Comment by drewwalters96** [comment]
This was completed in 720301
