### ISSUE TITLE
initinfra - remove document filtering 

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#132]
**Describe the bug**
With the current approach of using well delineated or segregated by  kustomization document bundles sets, the original intention of selecting  the initinfra artifacts using a flag should be deprecated.

**Steps To Reproduce**
alan@airship2-wh:~$ ./airshipctl --debug cluster initinfra --cluster-type=ephemeral
_Document filtered by selector "~G_~V_~K" found no documents_

**Expected behavior**
The above fails because we are trying to find a label that is currently not been used. Given that the entrypoint  is generated. by the initinfra + target cluster type args.

We expect to remove the implicit  document filter behavior in the cluster initinfra subcommand.

There is a Patchset https://review.opendev.org/#/c/715013/

**Comment by drewwalters96** [comment]
@jezogwza is this complete? It looks like https://review.opendev.org/715013 merged.

**Comment by jezogwza** [comment]
PS was merged.
