### ISSUE TITLE
Add Label phase injections in airshipctl.

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#133]
**Problem description (if applicable)**
Given the new approach of delivering document bundles that have been grouped or segregated as kustomization sets by the intended phase of airship in which they are delivered.

These feature calls for the injection of an appropriate label to mark the artifacts with. the appropriate phase label.

The label to be injected would be :

**_airshipit.org/phase: "..."_**

Where the phases are : 

- bootstrap
- initinfra
- ...

**Proposed change**
During the appropriate airshipctl commands such as cluster initinfra, or deliver we will inject the appropriate phase label.

**Potential impacts**
N/A

**Comment by teoyaomiqui** [comment]
can u assign this to me please

**Comment by jezogwza** [comment]
This is no longer needed given that we got this for free with the integration with cli-utils.
