### ISSUE TITLE
Document bundle ordering issue 

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#134]
**Describe the bug**
The document bundle function returns a resource map of documents.
The order in which they are sort does not  take into account precedence needs for artifacts on the cluster.
i.e. Create Namespace before artifact to be placed in the namespace.

**Steps To Reproduce**
Use **_airshipctl cluster ininfra_** to deliver documents, they will fail at first.
They are idempotent so eventually things will start working.

**Expected behavior**
Kustomize includes a transformer **_LegacyOrder_** that ensures documents are in the appropriate order i.e. namespace, service accounts, rbac, etc..
We need to ensure that transformer is used during the document bundle call.

- apply Kustomize Legacy Order plugin https://github.com/kubernetes-sigs/kustomize/blob/v3.2.0/pkg/commands/build/build.go#L162-L167

**Comment by teoyaomiqui** [comment]
@jezogwza i think this was already addressed here: 
https://github.com/airshipit/airshipctl/issues/131

**Comment by jezogwza** [comment]
YEs I see that. Closing thsi one. Implemented and merged https://review.opendev.org/#/c/715100/
