### ISSUE TITLE
Investigate Metal3 Operator Scheduling issue on Ephemeral Host

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#135]
**Describe the bug**
When deploying the airship infra on the  ephemeral host, it appears that the metal3 baremetal operator is taking a long time to be schedule. Although apparently eventually (>20mins)  it does schedule.

_**Warning FailedScheduling 22m (x3 over 24m) default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.    
Sai confirms BMO has:
node-role.kubernetes.io/master:NoSchedule
On node: Taints:             <none>**_

**Steps To Reproduce**
Deliver the initinfra generate yaml to teh ephemeral cluster.

**Expected behavior**
The operator should be up and running within mins.

**Comment by abailey011** [comment]
I think this can be closed.  After discussing with Sai, it seems this wasn't a bug.  Metal3 was waiting for coredns to remove that taint so the node is ready to be scheduled.

**Comment by drewwalters96** [comment]
Thanks @abailey011. Closing.
