### ISSUE TITLE
Multiple RedFish (Authentication missing, Eject media, Ignore TLS) Issues 

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#137]
**Describe the bug**
- Don't support authentication for redfish
- Code fixes this. Ejects and then inject media. - Error was Dont eject media, and if media is injected, injecting again will error and halt airshipctl
- Could not deal with validating certs when accessing redfish https URL
Likely need to try and validate certs by default, but offer a --ignore-tls (or whatever) for remotedirect
BMO also offers a skip_verify_ca (or some such) you need to turn on to make the BMO happy talking https to redfish via https://<ip>

**Steps To Reproduce**
Remotedirect against authenticated redfish URI
a

**Expected behavior**
There is a WIP  https://review.opendev.org/#/c/713711/  in progress that introduces potential fixes to these 3 issues. 
There is an alternative solution to the cert issues mentioned above..

**Comment by drewwalters96** [comment]
All of these items have been addressed; closing. We can open new issues for the beta milestone as they occur.
