### ISSUE TITLE
Add filtering to document bundle

### ISSUE THREAD

**Issue by alexander-hughes** [airshipit/airshipctl#14]
**Problem description (if applicable)**
Add capability to filter documents collected in document bundle command.

**Proposed change**
When document bundle is called, allow filtering to limit the collection to specific documents and return that subset of documents as a bundle.

**Potential impacts**
Document bundle command

**Comment by drewwalters96** [comment]
[Gerrit patch](https://review.opendev.org/704123)

**Comment by dukov** [comment]
https://review.opendev.org/#/c/704123
https://review.opendev.org/#/c/698658

**Comment by drewwalters96** [comment]
Work appears to be complete. Closing.
