### ISSUE TITLE
GetVirtualMediaId hard codes the available media types as 'Cd' when 'CD' is required for dell

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#141]
**Describe the bug**
The method GetVirtulMediaCD at https://github.com/airshipit/airshipctl/blob/master/pkg/remote/redfish/utils.go hardcodes teh return values.

func GetVirtualMediaID() (string, string, error) {
	// TODO: Sushy emulator has a bug which sends 'virtualMedia.inserted' field as
	//       string instead of a boolean which causes the redfish client to fail
	//       while unmarshalling this field.
	//       Insert logic here after the bug is fixed in sushy-emulator.
	return "Cd", "CD", nil
}

**Expected behavior**
Need to change this to follow the natural RedFish steps to 
_walk through the list of manager's virtual media resources and gets the ID of virtualmedia which has type "CD" or "DVD"_

**Comment by drewwalters96** [comment]
More information form @alanmeadows in #144 

**Describe the bug**
The redfish [GetVirtualMediaID](https://github.com/airshipit/airshipctl/blob/master/pkg/remote/redfish/utils.go#L51-L57) function hard codes a return of "Cd"

This may work for the sushy-emulator, but physical dell equipment requires a value of "CD"

We need to be walking the available VirtualMedia using the go-redfish library and returning the value dynamically from that response, whether it is "Cd" in sushy-emulator or "CD" in physical equipment.

```
	// The response from a real dell server
	//
	// GET https://1.2.3.4/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia
	//
	// {"@odata.context":"/redfish/v1/$metadata#VirtualMediaCollection.VirtualMediaCollection","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia","@odata.type":"#VirtualMediaCollection.VirtualMediaCollection","Description":"iDRAC Virtual Media Services Settings","Members":[{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/RemovableDisk"},{"@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD"}],"Members@odata.count":2,"Name":"Virtual Media Services"}
	//
	// It is unclear why we believe this is a sushy-emulator issue, a real dell server also has a boolean Inserted field:
	//
	// GET https://1.2.3.4/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD
	//
	// {"@odata.context":"/redfish/v1/$metadata#VirtualMedia.VirtualMedia","@odata.id":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD","@odata.type":"#VirtualMedia.v1_2_0.VirtualMedia","Actions":{"#VirtualMedia.EjectMedia":{"target":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.EjectMedia"},"#VirtualMedia.InsertMedia":{"target":"/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia"}},"ConnectedVia":"NotConnected","Description":"iDRAC Virtual Media Services Settings","Id":"CD","Image":null,"ImageName":null,"Inserted":false,"MediaTypes":["CD","DVD"],"MediaTypes@odata.count":2,"Name":"Virtual CD","WriteProtected":null}

```

**Comment by drewwalters96** [comment]
I am investigating this

**Comment by drewwalters96** [comment]
This is possible by parsing the resource ID from the URL. Solution on Gerrit, but I need to add more Redfish mocks to our unit tests: https://review.opendev.org/715995

**Comment by drewwalters96** [comment]
Ready for review https://review.opendev.org/715995
