### ISSUE TITLE
Add document bundle command

### ISSUE THREAD

**Issue by alexander-hughes** [airshipit/airshipctl#15]
**Problem description (if applicable)**
Airshipctl needs the functionality from Pegleg's collect command.

**Proposed change**
Add a command to airshipctl allowing the collection of documents.  These documents are referred to as a bundle.

**Potential impacts**
None

**Comment by drewwalters96** [comment]
[Gerrit patch](https://review.opendev.org/704123)

**Comment by dukov** [comment]
https://review.opendev.org/#/c/698658
https://review.opendev.org/#/c/705016

**Comment by jezogwza** [comment]
Refers to #16 
With the change to Phases and the introduction of the phase command this should be adjusted.

**Comment by ak3216** [comment]
@dukov with the delivery of #247, can we go ahead and close this one out? Thanks.

**Comment by dukov** [comment]
yes
