### ISSUE TITLE
Enhance Github Bot to add proper labels to move issues to InProgress

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#151]
Is it possible for the bot to besides adding the WIP label , change the status to In Progress?

**Comment by drewwalters96** [comment]
The bot code is here: https://github.com/ianpittwood/Gerrit-to-Github-Issues

**Comment by ian-howell** [comment]
[Pull Request](https://github.com/ianpittwood/Gerrit-to-Github-Issues/pull/3) to the bot - I'm working with @ianpittwood to test
