### ISSUE TITLE
Encoding of secret data in airshipctl config files

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#155]
**Problem description (if applicable)**
Airshipctl persist the secret data (manifest repo creds and k8s creds) in its configuration files (~/.airship/airshipconf and ~/.airship/kubeconfig) in cleartext.

**Proposed change**
For short term, the secret data in config files of **airshipctl** needs to be encoded in base64 as in kubectl so that there is at least a thin curtain in front of that data.

long term feature: https://github.com/airshipit/airshipctl/issues/156

**Potential impacts**
None

**Comment by jezogwza** [comment]
Modify pkg/config/config.go Method func (c *Config) ModifyAuthInfo(authinfo *AuthInfo, theAuthInfo *AuthInfoOptions) {

BAse64 encode the Password.

**Comment by sirajyasin** [comment]
I can work on this issue. could someone assign this to me
