### ISSUE TITLE
Validate that target cluster is ready after deployment via Ephemeral cluster

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#158]
**Problem description (if applicable)**
We need a mechanism to ascertain that the Target Cluster is ready , so that airship can move on to the next phase.

**Proposed change**
When using KubeadmControlPlane, we can find state using the following.
This issue is a request to incorporate this into the 
**_$ ./k get cluster/cluster -n metal3 -o json | jq '.status.controlPlaneReady'
true_**
This would be checked  after delivering the appropriate phase:
- In example this is `ephemeral/controlplane`
- As part fo the wait logic for asking ephemeral cluster to deploy the target , should include this as the criteria for saying that worked.

**Potential impacts**
The upcoming Pipeline or Run command needs to support a mechanism to understand and consume "wait logic" that might be different per phase.

This issue is essentially providing the opinionated need for a particular Phase.

**Comment by jingvar** [comment]
We should check pod statuses of the Target Cluster because "provisioned" Cluster doesn't means the Cluster is ready.

**Comment by jezogwza** [comment]
We should use this story as a good test example for the generic wait condition framework that Pavel is working on.

**Comment by ian-howell** [comment]
This is blocked by https://github.com/airshipit/airshipctl/issues/163

**Comment by mattmceuen** [comment]
@sirajyasin @ian-howell  - based on the conversation in the design call this morning, I believe our strategy for determining target cluster readiness will be to invoke kubectl against its apiserver (whatever we're doing down in RDM9 today).  Does that make this issue superfluous?  Or do you want to make your change under this one, Siraj?

**Comment by sirajyasin** [comment]
It has been added recently in a PS (@sreejithpunnapuzha )still in review stage
https://review.opendev.org/#/c/738696/33/tools/deployment/33_cluster_move_target_node.sh

@mattmceuen - is this sufficient  to check target cluster state ?

**Comment by mattmceuen** [comment]
@sirajyasin I think that is good enough for now.  It's a bit unfortunate to have to use kubectl for this instead of being able to rely on airshipctl wait, but I think we'll need to wait (pun intended) to see whether CAPI is willing to provide additional statusing when a node is in "ready for CNI deployment" state.

**Comment by jezogwza** [comment]
The introduction of airshipctl phase run includes waiting for an end condition, which implies the cluster is ready. This issues can be closed.
