### ISSUE TITLE
Design an approach for managing boot like action in general 

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#159]
**Problem description (if applicable)**
Need a generic mechanism that serves during initial provisioning and update for delivering bootscript like actions to the hosts os.
i.e.
KubeadmControlPlane sets up 'provisioning' bridge, but doesn't persist it

**Proposed change**
To be discussed

**Potential impacts**
Unknown at this time. But without a strategy or framework this can evolve into a mess.

**Comment by jingvar** [comment]
https://github.com/airshipit/airshipctl/issues/160

**Comment by drewwalters96** [comment]
Removing triage label so this does not resurface in the flightplan call. Leaving the design label so this can be discussed in the design call

**Comment by jezogwza** [comment]
This is no longer needed, we have paths forwards for this.. Using HostConfig, Image Builder, and delivering expected intentions via manifest.
