### ISSUE TITLE
Introduce WaitCondition

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#163]
**Problem description (if applicable)**
Nearly every step in airshipctl needs to understand when to continue to the next one, in our present state only the deployer can decide when to continue. 

**Proposed change**
Develop a configurable WaitCondition with which you would be able to specify what we are waiting and what state it should be in. as an example, we can have a WaitCondition struct, that would look simliar (to be developed):

```
type WaitCondition struct {
	// Seconds to wait before settings pipleine setting InProgress to false
	Delay int
	// ClusterResources is a list of resources to wait to become healthy in kubernetes cluster
	ClusterResources []Resource
	// Bundle
	Bundle BundleSelector
	// Exec is built on top of bash
	Exec
}

type BundleSelector struct {
	All bool
	Bundle Resources
}

type Resources struct {
	Group     string
	Version   string
	Kind      string
	Name      string
	Namespace string
}

type Exec struct {
	// Binary to executy
	Binary string
	// Retries number of tries before it is considered a failure
	Retries int
	// RetryTimeout seconds to wait for each retry before considering it as failure
	RetryTimeout int
}

type HttpHealthCheck struct {
	Url          string
	ResponseCode int
}

// Resource will be transformed to document.Selector and applied against bundle
type Resource struct {
	Group     string
	Version   string
	Kind      string
	Name      string
	Namespace string
}
```

With this idea, i think that airshipctl would be able to wait for anything that we want to wait, and we would be able to extend this object as much as weene

***NOTE:*** there is no implementation of this as of yet.

**Comment by drewwalters96** [comment]
Pavel is working on this

**Comment by ian-howell** [comment]
[PS](https://review.opendev.org/#/c/720280/)

**Comment by abailey011** [comment]
Additional patchset [here. ](https://review.opendev.org/#/c/726423/) Can this issue please be assigned to Pavel since he's working it?

**Comment by ian-howell** [comment]
This has been satisfied by [this commit](https://review.opendev.org/#/c/736054/). However, `cli-utils` has some limitations, so we may need to fall back on the original model. Closing this for now - if problems arise with the current implementation it should get a new issue.
