### ISSUE TITLE
Airshipctl persists old data when pointing to a new config file

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#165]
**Describe the bug**
After using the default config file, airshipctl persists data from the default config file when the user switches to a new config file using the `--airshipconf` flag.

**Steps To Reproduce**
1. Use airshipctl with the default config file.
2. Specify a new config file with different data using `--airshipconf`
3. Observe that data from the default config file has been added to the new config file.

**Expected behavior**
Data from one config file should not be written to a separate one.

**Environment**
- airshipctl Version: `992efae9710e1c264612c525ce2679cccc6a2c38`

**Comment by dukov** [comment]
you need to specify --kubeconfig flag since this file is considered as source of truth for airship config (see reconcile methods). Therefore airshipctl will populate kubeconfig data to new file.

**Comment by drewwalters96** [comment]
Shouldn’t it ignore the bootstrapOptions when doing that?

**Comment by dukov** [comment]
It should though....

**Comment by kvenkata986** [comment]
I am unable to assign it to myself, Can you please assign it to me ?

**Comment by drewwalters96** [comment]
@kvenkata986 all yours. Thanks!

**Comment by jezogwza** [comment]
Will close this appears to have become irrelevant with the move of config's to the document set,s
