### ISSUE TITLE
VM console log is broken

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#167]
When we switch to upstream image builder image, console log stopped working, you can observe this in
[https://a216c760f64cd66c40c4-21aea210631273030cc00dc607ec7d2f.ssl.cf1.rackcdn.com/713657/15/check/airship-airshipctl-gate-test/db016f8/primary/libvirt/libvirt-consoles/air-ephemeral-console.log](here)

I believe that this is due to incorrect tty configuration in grub parameters.

**Comment by teoyaomiqui** [comment]
this one is fixed by https://review.opendev.org/#/c/719055/

**Comment by drewwalters96** [comment]
Merged
