### ISSUE TITLE
Implement  airshipctl cluster move  

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#169]
**Problem description (if applicable)**
This command will implement the integration with the clusterctl move as well as execute the appropriate set of steps prior and post to complete the required move when using a metal3 provider.

**Proposed change**
The work Arvinder has been doing in the proposed metalctl will now be integrated into teh airshipctl

It will achieve the equivalent steps to the example below 

- Annotate the BMH CR 
    ./k annotate bmh -n metal3 rdm9r008c003 baremetalhost.metal3.io/paused=true

- Execute teh clusterctl move 
     clusterctl --v 20 move --kubeconfig=.airship/kubeconfig --to-kubeconfig=rdm9_kubeconfig --namespace=metal3

- - Update BMH Status 
./patch_curl 

-- Other steps as needed ..

**Potential impacts**
This introduces a new subcommand for airshipctl

**Comment by teoyaomiqui** [comment]
@jezogwza  is rdm9r008c003 ephemeral host name? Also, what is the content of `patch_curl` file?

**Comment by drewwalters96** [comment]
@jezogwza Arvinder will need to comment on this issue to assign it to him

**Comment by Arvinderpal** [comment]
@jezogwza you can assign this to me. Thanks.

**Comment by teoyaomiqui** [comment]
related issue: https://github.com/airshipit/airshipctl/issues/187

**Comment by jezogwza** [comment]
This was merged sometime ago.
