### ISSUE TITLE
Declarative credentials for kubeadm clusters

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#172]
**Problem description (if applicable)**
We need to generate the certificate or credentials that kubeadm cluster will utilize
Initialize for the Ephemeral Host cluster, but also for the Target cluster

The purpose of these issue is to define in airshipctl  :

- create a function that generates the certificate
- define the yaml artifact in which the certificate will live, including the document structure for this information
- identify the mechanism through which the certificate is integrated into the appropriate  host i.e injected into ephemeral cloud-init, or provided to KubeAdminControlPlaneTemplate

**Comment by drewwalters96** [comment]
Reviewed on flightplan call. Wait to assign until implementation details are hashed out

**Comment by ak3216** [comment]
This may be ready to close

**Comment by jezogwza** [comment]
This is already been done. We are delivering a custom ca through a function (See https://github.com/airshipit/airshipctl/blob/master/manifests/function/k8scontrol/cluster.yaml for an example).

Close this.
