### ISSUE TITLE
Pull Replacement Transformer config from resources

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#179]
**Problem description (if applicable)**
The airshipctl document replacement kustomize plug-in logic need to be integrated into airshipctl so that replacement logic can be managed and extended via airshipctl so that it can get its config from regular yaml resources rather than from a plugin config.

**Proposed change**
Build on enhancements from Issue #173 (Add airshipctl support for being invoked as a plugin) and update airshipctl to invoke kustomize with airshipctl configured as a plugin to apply replacement logic configured in yaml resources to template documents.

**Potential impacts**

**Comment by aodinokov** [comment]
kustomize allows to modify the plugin config just as a std resource and we're using this already to generate metal3 config.
nothing additional should be added - it's already OOB.

**Comment by jezogwza** [comment]
This idea was deemed as not achievable with the kustomize implementation for plugins. Replacement transformer integration remains as is in airshipctl.
