### ISSUE TITLE
20_run_test_runner.sh gate hangs at airshipctl-deploy-ephemeral-node : check kubectl version

### ISSUE THREAD

**Issue by aschiefe** [airshipit/airshipctl#189]
**Describe the bug**
when running tools/gate/20_run_test_runner.sh the execution hangs and does not return from the check kubectl version step

**Steps To Reproduce**
git clone & run gates 00_setup.sh, 10_build_gate.sh and 20_run_test_runner.sh

**Expected behavior**
The command should time out with a warning or error based on the lack of response, or the visualization needs to be corrected for this step

**Environment**
- airshipctl Version: 
- Operating System: Ubuntu 18.04
- Kernel version: v0.1.0
- Kubernetes Version: v1.16.2
- Go version: 1.14.2
- Hardware specs 24 vCPUs, 64GB RAM, vm

**Comment by realsystem** [comment]
Role "airshipctl-deploy-ephemeral-node" already has logic with:
  retries: 50
  delay: 20
Question: do you see iterations? Also part of log will be helpful.

**Comment by teoyaomiqui** [comment]
@aschiefe do you have a proxy in your environment ?

**Comment by aschiefe** [comment]
Yes I see iterations, but I didn't allow it to go all the way through 50 of them.  How long is it generally expected to take?

Yes there is a proxy in the environment which *should* have been properly injected into the containers.

**Comment by aschiefe** [comment]
This is the only error I have, what logs are you needing me to look at?

`fatal: [primary]: FAILED! => {"attempts": 50, "changed": true, "cmd": ["timeout", "20", "kubectl", "--kubeconfig", "/home/ubuntu/.airship/kubeconfig", "version"], "delta": "0:00:20.004623", "end": "2020-04-24 20:51:35.742099", "msg": "non-zero return code", "rc": 124, "start": "2020-04-24 20:51:15.737476", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}`

**Comment by ian-howell** [comment]
Related changes:
* https://review.opendev.org/723057
* https://review.opendev.org/722936

**Comment by drewwalters96** [comment]
Fixed in link patches
