### ISSUE TITLE
Validate that Configuration Exists during Config Load

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#194]
**Problem description**
Invalid variable configuration can cause null pointer issues leading to runtime errors (e.g. uninitialized maps).  When configuration is loaded specific sub-command validations are not performed until the sub-command operation.  There is a need to validate that configuration exists at the time it is loaded.
Reference issue #190 - Invalid config could cause runtime error

**Proposed change**
Enhance the airship config load to throw a warning if there is no configuration.

**Potential impacts**
By expanding the pool of upfront validations, we can eliminate runtime errors due to bad configurations at the sub-command level.

**Comment by ian-howell** [comment]
I believe this may be implemented already, but I'll take a look prior to closing

**Comment by ian-howell** [comment]
Closing as this is a duplicate of https://github.com/airshipit/airshipctl/issues/190
