### ISSUE TITLE
Enhance `airshipctl cluster init` with logging support

### ISSUE THREAD

**Issue by dukov** [airshipit/airshipctl#195]
**Problem description (if applicable)**
Currently execution or `airshipctl cluster init` command does not provide any logging

**Proposed change**
Enable logging messaged for `airshipctl cluster init`. Debug flag should be handled appropriately by increasing output verbosity level

**Potential impacts**
Cluster API components deployment logs will be visible.

**Comment by jezogwza** [comment]
This was merged with another patchset
