### ISSUE TITLE
Add EnsureComplete validation when setting config object in airshipctl secrets

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#216]
**Problem Description**
Reference issue #190 when invalid configuration returning runtime errors

**Proposed change**
When setting the config object, airshipctl secrets should use settings.Config.EnsureComplete() to validate that a config object is ready to use.

EnsureComplete does the following checks & returns an error if any one is not met.

    At least 1 Cluster is defined
    At least 1 AuthInfo (user) is defined
    At least 1 Context is defined
    At least 1 Manifest is defined
    The CurrentContext is set
    The CurrentContext identifies an existing Context
    The CurrentContext identifies an existing Manifest

**Potential impacts**
This will improve config object validations & identify potential issues upfront before continuing to execute the workflow.

**Comment by ian-howell** [comment]
is this really needed? The `airshipctl document secret` subcommand doesn't currently use the `Config` object - why do we need to verify it?

**Comment by raliev12** [comment]
> is this really needed? The `airshipctl document secret` subcommand doesn't currently use the `Config` object - why do we need to verify it?

Agree with Ian. We don't need such validation since `document secret` subcomannd doesn't use config object. We should close this one as invalid.

**Comment by lb4368** [comment]
I agree.  This can be closed as invalid
