### ISSUE TITLE
Create new repo for Helm Chart management in Airship

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#219]
**Problem description (if applicable)**
Need a way to manage helm charts in airship that require changes from upstream versions.

**Proposed change**
Create a new airship helm chart repo that would:

    - Host forked or new charts. i.e. DEX - https://github.com/project-azorian/dex-aio/tree/master/dex-aio (which combines dex with mintel's authenticator)

    - Refer to a list of Airship referred to or used by charts. i.e. Rook

    - Implement CI/CD that would gate both types of charts (hosted by/refered by Airship).

**Potential impacts**
This would allow for a process for a new chart needed in airship
1. Identify the source for it upstream (Repo / Helm Hub) and try to use it.
2. If changes are needed, try to patch the upstream source.
3. If changes are difficult to achieve in source, then fork the chart into this airship repo and become the source for airship.

**Comment by jezogwza** [comment]
Will create a new repo named TBD. Will be discussed in the IRC meeting.

**Comment by abailey011** [comment]
This was discussed in the IRC meeting on 5/26/2020.  There was no concern with creation of this new project.  @mattmceuen will take ownership of this.

**Comment by mattmceuen** [comment]
Project creation request:  https://review.opendev.org/#/c/731236/

After that goes through, I'll make an initial commit to set up the project, add the core team, and it'll be open for business.

**Comment by alanmeadows** [comment]
Closing this as the repo now exists.
