### ISSUE TITLE
Add bash based control plane phase deployment to gate tests

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#229]
**Problem description (if applicable)**
We need to develop bash script to deploying control plane to ephemeral cluster. and integrate it with future gate bash script runner mentioned in https://github.com/airshipit/airshipctl/issues/223

**Proposed change**

In manifests we should add following resources:

- Metal3Cluster
- Metal3MachineTemplate
- Cluster
- KubeadmControlPlane

In tools/gates we should add bash script which would essentially do single command:
```
airshipctl --debug phase apply controlplane
```
this command would apply manifests described above the the ephemeral cluster

**Comment by slfletch** [comment]
Can someone assign this issue to me.

**Comment by sreejithpunnapuzha** [comment]
@slfletch all yours..

**Comment by teoyaomiqui** [comment]
this can be closed now, control plane is being deployed in CICD
