### ISSUE TITLE
Arishipct images: remove cloud-init package installation from unstable deb repository

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#241]
**Problem description**
In airship images repository,  we install cloud-init from unstable repository, as a result, on May 14, we had problems with CI as unstable repository cloud-init package was broken, and could not be installed, which led to CI failures the whole day

**Proposed change**
As debian buster (latest stable) distribution, does supply only old versions of cloud init 18.*.*, we need an alternative source of the package. 

I propose that we install it from source code, using git clone, then installing requirements etc...

**Potential impacts**
Since we are will not be using apt to manage packages for cloud-init, we may run into some dependency issues and conflicts.

**Comment by teoyaomiqui** [comment]
working version that we want to have is 20.1+

**Comment by noskovao** [comment]
I'll pick up this.

**Comment by noskovao** [comment]
https://review.opendev.org/729289

**Comment by alanmeadows** [comment]
Can someone explain why we need cloud-init from the unstable repository in the first place? Can someone articulate why  cloud-init from the stable repository work for our needs?

**Comment by teoyaomiqui** [comment]
@alanmeadows it has 18 version, which fails to consume openstack style network data. So we used 20.1 which works. Right now @noskovao is working on looking into all possible solutions, including getting version 18 from stable to work

**Comment by intlabs** [comment]
this simplest here would be to base the image off testing aka bullseye - which is what ubuntu 18.04 is a snapshot of - and contains v20.1 of cloud-init.

**Comment by teoyaomiqui** [comment]
The appropriate commits were merged, and issue can be closed now
