### ISSUE TITLE
Integrate ImageBuilder into airshipctl

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#248]
**Problem description (if applicable)**
To provide a declarative interface for building images, integrate the ImageBuilder patchset with isogen.yaml to support airshpctl image generation. 

**Proposed change**
Patchset https://review.opendev.org/#/c/730777 has been created to provide the ImageBuilder command set. It's currently supporting ubuntu based airship hosts.

**Comment by ak3216** [comment]
See https://github.com/airshipit/images/issues/1 for Image Builder itself.

**Comment by mf4716** [comment]
@craiganderson , can you provide an update?

**Comment by craiganderson** [comment]
Image-builder has been successfully implemented per PS linked in the description.
Also, the airshipctl integration for building ISOs has been successfully implemented per https://review.opendev.org/c/airship/airshipctl/+/758782
