### ISSUE TITLE
Define Manifest representation of Image intentions

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#249]
**Proposed Change**
To support #248 Image Builder integration, need to define manifests that declare image intentions. This would include variables like partition layouts, package repositories, file systems, k8s version, etc.

**Potential impacts**
This will move the declarations from configuration to manifests.

**Acceptance Criteria**
At a minimum, the following parameters should be supported at image creation time. To update, in most cases, a new image will be generated, but some parameters will also have host-config support for day 2 operations or emergency updates.
- Docker 
- Containerd 
- Ubuntu 
- Kernel settings
- Intel i40e driver 
- Other NIC drivers
- Specifying system software packages (including what has been traditionally supported by mini-mirror)
- apt source location
- Sysctl settings\*
- Permissions (perms) settings/overrides
- Limits settings\*
- Apparmor specification/lifecycling
- CNI version\*
- K8s version\*
- Banner\*
- Grub\*
- Ethtool actions (as part of cloud init network data)**
- Cloud init metadata**
- Cloud init user data**
- DNS***
- QCOW limits***
- Partitions***

**Comment by lb4368** [comment]
Per 6/22/2020 SIG-YAML call, the Phase Image Definition manifest needs to be designed to feed image builder.  Image definitions can be split as ephemeral or target.  See https://go.gliffy.com/go/publish/13315097.

**Comment by ak3216** [comment]
Add image builder entries from https://docs.google.com/spreadsheets/d/1BQRadxOOzvRq8C6j3fe4xQ1f4AjSCfAyWG73U15pIho/edit#gid=0 as acceptance criteria

**Comment by mf4716** [comment]
@craiganderson , can you provide an update?

**Comment by craiganderson** [comment]
This issue may be closed after merging of https://review.opendev.org/c/airship/airshipctl/+/765511 which is now awaiting the completion of code review.

**Comment by craiganderson** [comment]
Merged into airshipctl & completed
