### ISSUE TITLE
Make airshipconfig and kubeconfig file modifications co-dependent

### ISSUE THREAD

**Issue by ianpittwood** [airshipit/airshipctl#25]
**Problem description (if applicable)**
Writing to the airshipconfig and kubeconfig in `PersistConfig()` can result in modifications to only the airshipconfig file if an error occurs. This will result in differences between the airshipconfig and kubeconfig.

**Proposed change**
A possible solution is to make the modifications to each file codependent. A backup of each file could be created before modifications are made and restored if an error occurs.

Source: FIXME(howell), pkg/config/config.go, L355-359

**Comment by ansumanbebarta** [comment]
I was checking the issue and found that the below source is no longer there.
Source: FIXME(howell), pkg/config/config.go, L355-359
I could find the commit which modified the FIXME.

https://github.com/airshipit/airshipctl/commit/32ef58435dc0f726098c8729843304955f014243#diff-091ace02b49a46f55f2586cfec89a160L355

**Comment by ianpittwood** [comment]
It seems that this was already fixed based on @ansumanbebarta 's comment
