### ISSUE TITLE
Config Refactor: PhasePlan management for GF/BF scenarios

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#258]
**Proposed change**
There needs to be a method for managing phase plan documents as it relates to greenfield vs. brownfield deployments. 

One approach would be to have different phase plan documents for each deployment type. Another approach would be to just manage what's applicable for GF vs. BF vs. both within a single phase plan document via a deployment-type indicator.

**Comment by jezogwza** [comment]
Given that we refactor phases and phase plans to exist or be defined within the type layer, the difference between a phaseplan for GF vs BF is essential for the existence of a different phase plan. This is a non-issue.  We. can defer the need for the creation of these phase plans until we see the need to articulate or have the use case for treasuremap.
