### ISSUE TITLE
Where does HostProfile Information live in Airship 2.0

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#274]
Need to flesh out the design of the host profile as it relates to various configuration parameters (grub, CPU & memory resource allocation, networking & local storage configuration, kubernetes node selector, etc.)

**Comment by ak3216** [comment]
There are several other RDM9 issues from Craig A that are likely dependent on this one

**Comment by ak3216** [comment]
Additional requirements from the  6/23 design call. There was a question of whether or not RAID/BIOS should be part of the Host Profile (Raised by Noor Muhammad)
- The agreed upon direction is this is considered HostProfile type information & should leverage the host generator approach to inject the profile data into the host catalogue document.
-- Could the HostProfile be essentially thought out as the https://review.opendev.org/#/c/735033/15/manifests/function/hostgenerator-m3/hosttemplate.yaml
-- HostGenerator Patchsets :
--- https://review.opendev.org/#/c/735033/
--- https://review.opendev.org/#/c/737092/

- There was also a question as to whether or not we need a HardwareProfile vs HostProfile
-- Can HostProfile essentially carry vendor info (like label/etc) as needed?
-- The desire is for hardware related data should leverage the HostGenerator Template mechanism somehow.
-- ClassificationController for Profile association when needed.

**Comment by pramchan** [comment]
Metal uses hardware profile refer.
https://github.com/metal3-io/baremetal-operator/blob/master/pkg/hardware/profile.go

**Comment by demonCoder95** [comment]
@ak3216 Thank you for recording the summary here Andrew!

**Comment by jezogwza** [comment]
We can close this, there is an approach been discussed within the context of the Image Builder. manifest integration that overlaps with this.
