### ISSUE TITLE
Optimize memory usage for gating

### ISSUE THREAD

**Issue by jingvar** [airshipit/airshipctl#287]
**Problem description (if applicable)**
Some Linux distributions and Kubernetes versions use more RAM. 

**Proposed change**
Add to manifests/function/ephemeral/secret.yaml

    - mkdir -p /mnt/vda/var/lib/kubelet/ /var/lib/kubelet/
    - mount --bind /mnt/vda/var/lib/kubelet/ /var/lib/kubelet/

A detailed description of the new, requested behavior.

**Potential impacts**
Potential security or performance related impacts.

**Comment by drewwalters96** [comment]
Closing as this has merged
