### ISSUE TITLE
airshipctl and clusterctl integration

### ISSUE THREAD

**Issue by alanmeadows** [airshipit/airshipctl#29]
**Problem description (if applicable)**
For both ephemeral and target invokations of `airshipctl cluster initinfra` as well as a non-existent pivot command we intend to integrate the [clusterctl](https://github.com/kubernetes-sigs/cluster-api/tree/master/cmd/clusterctl) pkg as a library.

While the `clusterctl` pkg continues to develop, this issue represents the effort of beginning that integration to understand the specific gaps remaining, especially the work we need to accomplish upstream within `clusterctl`. 

**Proposed change**
For the `airshipctl cluster initinfra` commands, leverage the `clusterctl` library to perform the init, effectively equivalent to a `clusterctl init`.  This will initially be equivalent to a `kubectl apply` of the provider resources, and we will build on the gaps remaining for leveraging metal3-io as a provider to just providing that - for instance, ensuring that the `baremetal-operator`, `ironic`, and so on are also instantiated, as well as `BareMetalHost` records to support subsequent `Machine` provisioning.

Within `airshipctl`, there is a need to be able to feed provider resources to a library like `clusterctl`. There has been work done upstream in `clusterctl` to support pulling provider resources from a local file system.  We need to understand whether this will work for the way `airshipctl` renders documents through Kustomize and emits them as `Document` objects as part of a bundle - see the following [pull request](https://github.com/kubernetes-sigs/cluster-api/pull/1963/) in clusterctl.  Will we create a fake filesystem and provide that to `clusterctl` or enhance it upstream to support a YAML byte stream?

**Potential impacts**
There may be requirements for `clusterctl` upstream that may need to be solved locally in `airshipctl`.

**Comment by jezogwza** [comment]
Already there are separate issue closed or in progress for integrating clusterctl init and clusterctl move.
