### ISSUE TITLE
airshipctl config use-context doesn't switch current context in kubeconfig

### ISSUE THREAD

**Issue by realsystem** [airshipit/airshipctl#290]
**Describe the bug**
When I run "airshipctl config use-context <cluster_name>" the current context is not switched in kubeconfig. I need to run any other config command which is internally running the config reconcile function to update kubeconfig. The problem is in the use-context CLI command, it calls airconfig.PersistConfig() and updates only airship config file. kubeconfig should be updated respectively by running c.reconcileConfig() or something similar.

**Steps To Reproduce**
Create two contexts and try to switch between them.
Run command: `airshipctl config use-context target-cluster-admin@target-cluster`

**Expected behavior**
Current context should be switched in airship config file and kubeconfig file.

**Environment**
- airshipctl Version: master
- Operating System: ubuntu

**Comment by drewwalters96** [comment]
Since we will be storing the context in the document set, we should remove this subcommand. We will replace with a new issue per the flightplan call
