### ISSUE TITLE
Install airshipctl as kustomize plugins

### ISSUE THREAD

**Issue by jingvar** [airshipit/airshipctl#298]
**Problem description (if applicable)**
We can't use airshipctl's  features of substitution and generation and with 'manifests'.

**Proposed change**
Add wrappers for ReplacementTransformer and Templater.

**Potential impacts**
Potential security or performance related impacts.

**Comment by jingvar** [comment]
`
`~/airshipctl# ./tools/gate/20_run_gate_runner.sh `
TASK [airshipctl-run-script : Run script ./tools/deployment/24_build_ephemeral_iso.sh] ******************************************************************************************************
fatal: [primary]: FAILED! => {"changed": true, "cmd": "set -xe;\n./tools/deployment/24_build_ephemeral_iso.sh\n", "delta": "0:00:00.242849", "end": "2020-07-17 09:19:23.479206", "msg": "non-zero return code", "rc": 1, "start": "2020-07-17 09:19:23.236357", "stderr": "+ ./tools/deployment/24_build_ephemeral_iso.sh\n+ export USER_NAME=root\n+ USER_NAME=root\n+ ISO_DIR=/srv/iso\n+ CLEANUP_SERVE_DIR=false\n+ SITE_NAME=test-site\n+ sudo rm -rf /srv/iso\n+ sudo mkdir -p /srv/iso\n+ sudo chmod -R 755 /srv/iso\n+ sudo chown -R root /srv/iso\n+ echo 'Build ephemeral iso'\n+ airshipctl image build --debug\nplugin /root/.airship/kustomize-plugins/airshipit.org/v1alpha1/replacementtransformer/ReplacementTransformer fails to load: plugin: not implemented", "stderr_lines": ["+ ./tools/deployment/24_build_ephemeral_iso.sh", "+ export USER_NAME=root", "+ USER_NAME=root", "+ ISO_DIR=/srv/iso", "+ CLEANUP_SERVE_DIR=false", "+ SITE_NAME=test-site", "+ sudo rm -rf /srv/iso", "+ sudo mkdir -p /srv/iso", "+ sudo chmod -R 755 /srv/iso", "+ sudo chown -R root /srv/iso", "+ echo 'Build ephemeral iso'", "+ airshipctl image build --debug", **"plugin /root/.airship/kustomize-plugins/airshipit.org/v1alpha1/replacementtransformer/ReplacementTransformer fails to load: plugin: not implemented"], "**stdout": "Build ephemeral iso", "stdout_lines": ["Build ephemeral iso"]}`

**Comment by jingvar** [comment]
https://review.opendev.org/#/c/740703

**Comment by drewwalters96** [comment]
This one is likely completed

**Comment by ak3216** [comment]
Closing due to being reopened by abandoned patchset
