### ISSUE TITLE
Syntax error: manifest-schema.json

### ISSUE THREAD

**Issue by alexander-hughes** [airshipit/airshipctl#307]
**Describe the bug**
There is a mismatch of opening and closing braces in airshipctl/bin/treasuremap/tools/deployment/seaworthy-virt/airship_gate/manifest-schema.json

**Steps To Reproduce**
Grep for opening and closing braces, listing counts of each.

```
ubuntu@ubuntu-VirtualBox:~/projects/airshipctl$ grep '{' bin/treasuremap/tools/deployment/seaworthy-virt/airship_gate/manifest-schema.json  | wc -l
33
ubuntu@ubuntu-VirtualBox:~/projects/airshipctl$ grep '}' bin/treasuremap/tools/deployment/seaworthy-virt/airship_gate/manifest-schema.json  | wc -l
32
```

**Expected behavior**
Opening braces should have matched closing braces to be considered a correct document.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):

**Comment by niharikabhavaraju** [comment]
I would like to work on this please assign to me.

**Comment by alexander-hughes** [comment]
> 
> 
> I would like to work on this please assign to me.

Thanks for picking this up!

**Comment by alexander-hughes** [comment]
This work is not valid, the bin directory locally was not removed prior to running this test. After deleting the bin directory and running through the make targets I can not reproduce this file.
