### ISSUE TITLE
implement airshipctl cluster move

### ISSUE THREAD

**Issue by alanmeadows** [airshipit/airshipctl#31]
**Problem description (if applicable)**
As part of the cluster-api workflow, `airshipctl` will require an `airshipctl cluster move` implementation to move resources from the ephemeral to the target cluster.

**Proposed change**
This expands on integration with the `clusterctl` integration (#29).  It will leverage the `clusterctl` pkg in order to perform a `clusterctl move` but it must also care for the `BareMetalHost` object of the target node which would be provisioned by the ephemeral node to ensure it is transferred to the target cluster along with the inventory data that was gathered.  There is a known issue right now where the status of the node, namely the fact that it was successfully provisioned, is not transferred.  There is a known out-of-band solution that exists, effectively creating the `BareMetalHost` entry, and then patching the status as a subsequent step.  This requires the following flow:

- Scale down the operators in the target cluster so provisioning does not occur during this process, including the BMO, and CAPBM
- Transfer the BareMetalHost record for the target node from the ephemeral cluster to the target cluster
- Patch the record with a success status so it isn't picked up by operators for provisioning
- Scale the operators back up
- Power off the ephemeral node so it does not interfere with further target cluster provisioning

**Potential impacts**
None

**Comment by jgu17** [comment]
@alanmeadows I can start the work on this story but wanted to check with you if there is any dependency on other issues before this work can start?

**Comment by jgu17** [comment]
is this the same as or overlap with https://github.com/airshipit/airshipctl/issues/169

**Comment by drewwalters96** [comment]
Since this is a duplicate, closing.
