### ISSUE TITLE
Documentation of a quickstart Guide for trying out airshipctl

### ISSUE THREAD

**Issue by sb1975** [airshipit/airshipctl#314]
**Describe the bug**

As it stands its not very easy if anyone wants to run airshipctl and build a simple cluster on either CAPD,Azure or GCP.
It would be nice and help grow the interest if we can include a quick start guide to quickly onboard anyone willing to check how it works..

**Steps To Reproduce**
Minimal steps to reproduce the issue.

**Expected behavior**
Documentation for quickstart of airshipctl.

**Environment**
- airshipctl Version:
- Operating System:
- Kernel version:
- Kubernetes Version:
- Go version:
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):

**Comment by drewwalters96** [comment]
Some of the existing patches have READMEs. Please see those before starting work on this one

**Comment by muly** [comment]
i'd like to start working on this issue. could you please assign this to me?

**Comment by drewwalters96** [comment]
@muly All yours!

**Comment by sb1975** [comment]
Simple steps could be as below :
git clone https://review.opendev.org/airship/airshipctl
cd airshipctl

Gate deployment steps:
1. ./tools/gate/00_setup.sh
2. ./tools/gate/10_build_gate.sh
3. sudo ./tools/deployment/01_install_kubectl.sh
4. sudo ./tools/deployment/21_systemwide_executable.sh
5. sudo ./tools/deployment/22_test_configs.sh
=> After this change the targetPath to path to airshipctl dir in config
sudo vi ~/.airship/config => update targetPath
6. sudo ./tools/deployment/24_build_ephemeral_iso.sh
7. sudo ./tools/deployment/25_deploy_ephemeral_node.sh
8. sudo ./tools/deployment/26_deploy_metal3_capi_ephemeral_node.sh
9. sudo ./tools/deployment/30_deploy_controlplane.sh
10. sudo ./tools/deployment/31_deploy_initinfra_target_node.sh
11. sudo ./tools/deployment/32_cluster_init_target_node.sh

However it would be good to document and explain the steps.

**Comment by sumitjadhav1** [comment]
Additionally how to make use of all configuration files for real hardware (like Dell PowerEdge Servers).
Currently we are unable to introspect/onboard real nodes. Please refer [Issue#300](https://github.com/airshipit/airshipctl/issues/300)

**Comment by ak3216** [comment]
@sumitjadhav1, @lb4368 & I have started a patchset that provides a framework for developing a quickstart guide/flow documentation. I think that as the beta release gets delivered with some of the major refactoring changes to config, phases & the document set, we can start building out the details. Happy to discuss if you're interested. 
https://review.opendev.org/#/c/735399/

**Comment by slfletch** [comment]
I would look at the airship in a pod patchset that has already been started. @ian-howell is currently continuing development on it.  

It's to the point of running the following scripts in a Kubernetes pod.
/tools/gate/00_setup.sh
./tools/gate/10_build_gate.sh
sudo ./tools/deployment/01_install_kubectl.sh
sudo ./tools/deployment/21_systemwide_executable.sh
sudo ./tools/deployment/22_test_configs.sh
=> After this change the targetPath to path to airshipctl dir in config
sudo vi ~/.airship/config => update targetPath
sudo ./tools/deployment/24_build_ephemeral_iso.sh
sudo ./tools/deployment/25_deploy_ephemeral_node.sh

**Comment by ak3216** [comment]
We have an increasing number of people starting to trial airshipctl and are looking for some documentation on how to get started. It might be good to at least get the updated list of scripts to run on https://docs.airshipit.org/airshipctl/architecture.html#example-usage as what is out there today is not valid.

**Comment by drewwalters96** [comment]
@muly Is there anything we can do to help complete this issue?

**Comment by sb1975** [comment]
https://review.opendev.org/c/airship/airshipctl/+/763923
The above PS outlines the instructions to build a All-in-one VM setup in Local machine alongwith steps towards how to validate the setup as well how to use the target cluster and deploy workloads on it.
This issue may be closed as completed.

**Comment by ak3216** [comment]
Closing per merge.
