### ISSUE TITLE
developer friendly gate hook scripts

### ISSUE THREAD

**Issue by alanmeadows** [airshipit/airshipctl#32]
**Problem description (if applicable)**
The `airshipctl` end-to-end test is currently launched by Zuul infrastructure.  We need to ensure these same gates can act as developer friendly scripts to launch a virtualized `airshipctl` environment locally.

**Proposed change**
While the ansible gate playbooks can be launched by hand with a series of flags and environmental settings, we need to make this more approachable to new developers.  This issue proposes a series of simple idempotent scripts that developers can run which will exercise the gate locally, without Zuul infrastructure, e.g.

```
tools/gate/01_create_iso.sh
tools/gate/02_launch_ephemeral_node.sh
...
```

**Potential impacts**
None

**Comment by teoyaomiqui** [comment]
We have decided that we will use bash for that, correct? because right now there is some work going on around ansible roles instead of bash

**Comment by alanmeadows** [comment]
I think the point here is that these simple bash scripts could simply call the ansible roles that are being created.  It provides a simple way for developers unfamiliar with ansible, the right environment variables, flags, and so on to set to be able to use those roles.

**Comment by realsystem** [comment]
https://review.opendev.org/709636

**Comment by realsystem** [comment]
scripts has been merged long time ago, closing
