### ISSUE TITLE
manifest line getting deleted from airship config on doing airshipctl cluster init

### ISSUE THREAD

**Issue by shashipratap** [airshipit/airshipctl#321]
**Describe the bug**
following the steps as listed in the https://review.opendev.org/#/c/737864/42/docs/azure/azure-integration.md and decided to use the default config file with the repo details put in place.

On running “airshipctl cluster init”, the config document (config_FirstCreate) was changed automatically to reflect the “Kind” cluster details. However within this block
      contexts:
        kind-airship2-kind-api:
        contextKubeconf: kind-airship2-kind-api_target
 
      “manifest: azure_manifest” was missing even when it was present in the first config document provided.

this resulted in below error

![image](https://user-images.githubusercontent.com/32389950/89423458-24a15900-d754-11ea-96ac-e4942f88decf.png)

**Steps To Reproduce**
Clone  and fetch the above commit and then do a airshipctl config init on a ubuntu machine

**Expected behavior**
airschipctl config init should not give any error

**Environment**
- airshipctl Version: airshipctl:   v0.1.0
- Operating System: Ubuntu
- Kernel version: 5.3.0-1034-azure
- Kubernetes Version: 1.18
- Go version: 1.13
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):  4 G ram on management cluster machine hosting kind cluster ,
, 1 CPU , Azure VM

**Comment by niharikabhavaraju** [comment]
I would like to work on this, please assign it to me

**Comment by lb4368** [comment]
@niharikabhavaraju - You are assigned.  Thanks!

**Comment by mf4716** [comment]
@niharikabhavaraju (Niharika), are you actively working on this bug?  Any assistance needed to move this forward?  I'll reach across offline too.

**Comment by niharikabhavaraju** [comment]
I'm no longer able to reproduce this issue, The wip patch set mentioned in the issue description is now obsolete @mf4716

**Comment by ak3216** [comment]
Closing per not being able to reproduce the issue. Can reopen if it occurs again.
