### ISSUE TITLE
Worker node 'node03' not coming up in ready state

### ISSUE THREAD

**Issue by Ashughorla** [airshipit/airshipctl#352]
**Describe the bug**
Create setup using 00_setup.sh , 10_build_gate.sh and 20_run_gate_runner.sh scripts.
At last script while deploying worker node using 34_deploy_worker_node.sh script. node03 is not coming up in ready state.

**Steps To Reproduce**
Deployed airshipctl setup with changes present at https://review.opendev.org/#/c/748421/

**Expected behavior**
Worker node should come up in ready state.

**Environment**
- airshipctl Version: v0.1.0
- Operating System: Ubuntu 18.04.4
- Kernel version: 5.3.0-28-generic
- Kubernetes Version: 1.18
- Go version: 1.14
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): CPU(s) : 16 , 98GB RAM, VM

**Comment by Ashughorla** [comment]
[air-worker-1-console.log](https://github.com/airshipit/airshipctl/files/5257968/air-worker-1-console.log)

Attaching logs of air-worker-1

**Comment by Ashughorla** [comment]
Adding logs for success and fail air-worker-1 node.
[success_air-worker-1-console.log](https://github.com/airshipit/airshipctl/files/5262029/success_air-worker-1-console.log)
[failed_air-worker-1-console.log](https://github.com/airshipit/airshipctl/files/5262030/failed_air-worker-1-console.log)
Line number : 1503

**Comment by Ashughorla** [comment]
BMH node03 yaml
[bmh.log](https://github.com/airshipit/airshipctl/files/5262356/bmh.log)

**Comment by Ashughorla** [comment]
node03-bmc-secret 
[Uploading node03-bmc-secret.log…]()

**Comment by realsystem** [comment]
@Ashughorla did you try to deploy without patchset that you mentioned in the description? I mean pure master of airshipctl. Need to have understanding is it in issue with this PS or some common issue.

**Comment by Ashughorla** [comment]
@realsystem yes, pure master of airshipctl works fine.
with the changes of https://review.opendev.org/#/c/748421/ patchset, I am facing issue.

**Comment by Ashughorla** [comment]
Issue got resolved.
Got solution with updated BMO package version in HWCC.
