### ISSUE TITLE
Add beta tag to Airshipctl quay.io image

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#353]
Update the quay.io Airshipctl image to add the beta tag once all beta patchsets have been merged.

Dependent on merging the following patchsets:
-    https://review.opendev.org/#/c/753504/
-    https://review.opendev.org/#/c/752314/

Link to images can be found here:
https://quay.io/repository/airshipit/airshipctl?tab=tags

**Comment by jezogwza** [comment]
Let's close this, someone is tagging as I type.

**Comment by mattmceuen** [comment]
[madgin@leviathan:~/airship2/airshipctl-master/manifests/site/test-site/target]$ docker pull **quay.io/airshipit/airshipctl:v2.0.0-beta.1**
v2.0.0-beta.1: Pulling from airshipit/airshipctl
88c9d56e246d: Pull complete
Digest: sha256:40646a74e99964d6a3be3ded01a52ed7f67d89e801d273c54f6356eb07a8c0c1
Status: Downloaded newer image for quay.io/airshipit/airshipctl:v2.0.0-beta.1
quay.io/airshipit/airshipctl:v2.0.0-beta.1
