### ISSUE TITLE
Investigate GitHub integration options with OpenDev Gerrit

### ISSUE THREAD

**Issue by ianpittwood** [airshipit/airshipctl#36]
**Problem description (if applicable)**
We are currently using GitHub for our issues, but we still have OpenStack Storyboard enabled on our project in Gerrit. Ideally, the Storyboard for this project should be disabled and additional integration with GitHub (possibly via jeepyb) should be investigated.

**Proposed change**
Research ways to better integrate our GitHub Issues with OpenDev Gerrit.

**Comment by ianpittwood** [comment]
I found [this page](https://docs.openstack.org/infra/system-config/jeepyb.html) that suggests we can flip the `has-issues` setting to true to indicate we use GitHub Issues.

**Comment by ianpittwood** [comment]
I decided to ask about the `has-issues` functionality in #openstack-infra chat. It sounds like `has-issues` is deprecated and that OpenDev does not wish to support non-OSI issue trackers, such as GitHub Issues. After further inquiry, it seems we could probably build some homebrewed integration via Zuul if we wish to do so.

[openstack-infra-chat_2-12-20.txt](https://github.com/airshipit/airshipctl/files/4192862/openstack-infra-chat_2-12-20.txt)

**Comment by ianpittwood** [comment]
I created a separate set of scripts that can be run as a cron job to update Github Issues with Gerrit change data.

https://github.com/ianpittwood/Gerrit-to-Github-Issues

**Comment by jezogwza** [comment]
https://review.opendev.org/#/c/707453/17/CONTRIBUTING.md

There is a "bot" now integrating this.
Follow guidelines in doc above.
