### ISSUE TITLE
airshipctl "make docker-image-test-suite" failing because of a hardcoded AT&T proxy

### ISSUE THREAD

**Issue by bravinash82** [airshipit/airshipctl#371]
**Describe the bug**
The command "make docker-image-test-suite" fails to download a go mod "github.com/Azure/go-autorest/autorest@v0.11.7" since it assumes the make env is behind a proxy.

**Steps To Reproduce**
As described in link "https://docs.airshipit.org/airshipctl/developers.html", I ran the command "make docker-image-test-suite"
I get the following error: 

root@k8s:~/community/airshipctl# make docker-image-test-suite
Sending build context to Docker daemon    113MB
Step 1/13 : ARG GO_IMAGE=docker.io/golang:1.13.1-stretch
Step 2/13 : ARG RELEASE_IMAGE=scratch
Step 3/13 : FROM ${GO_IMAGE} as builder
1.13.1-stretch: Pulling from library/golang
092586df9206: Pull complete
ef599477fae0: Pull complete
4530c6472b5d: Pull complete
d34d61487075: Pull complete
89c6ec31b9e9: Pull complete
42ee48cf5b6b: Pull complete
54293c570669: Pull complete
Digest: sha256:fb43085cff7d427476d069bd4d020281956bfbcc99a83cf9d6c69b53df76f69f
Status: Downloaded newer image for golang:1.13.1-stretch
 ---> f8c4e1a86e6d
Step 4/13 : LABEL org.opencontainers.image.authors='airship-discuss@lists.airshipit.org, irc://#airshipit@freenode'       org.opencontainers.image.url='https://airshipit.org'       org.opencontainers.image.documentation='https://docs.airshipit.org/airshipctl/'       org.opencontainers.image.source='https://opendev.org/airship/airshipctl'       org.opencontainers.image.vendor='The Airship Authors'       org.opencontainers.image.licenses='Apache-2.0'
 ---> Running in 528394e3179a
Removing intermediate container 528394e3179a
 ---> 153aabcde59f
Step 5/13 : COPY ./certs/* /usr/local/share/ca-certificates/
 ---> 0d5803a5a622
Step 6/13 : RUN update-ca-certificates
 ---> Running in 089351a50fe2
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 089351a50fe2
 ---> 4ca887eeac52
Step 7/13 : SHELL [ "/bin/bash", "-cex" ]
 ---> Running in ae81288826ba
Removing intermediate container ae81288826ba
 ---> b5ffebaadd5d
Step 8/13 : WORKDIR /usr/src/airshipctl
 ---> Running in db63d882b898
Removing intermediate container db63d882b898
 ---> a3517d5be9f7
Step 9/13 : COPY go.mod go.sum /usr/src/airshipctl/
 ---> 15620d2d7853
Step 10/13 : RUN go mod download
 ---> Running in 7ddde73ff3bc
+ go mod download
**go: github.com/Azure/go-autorest/autorest@v0.11.7: Get https://proxy.golang.org/github.com/%21azure/go-autorest/autorest/@v/v0.11.7.mod: proxyconnect tcp: dial tcp: lookup one.proxy.att.com on 192.168.2.1:53: no such host**
Removing intermediate container 7ddde73ff3bc
The command '/bin/bash -cex go mod download' returned a non-zero code: 1
make: *** [Makefile:125: docker-image] Error 1

**Expected behavior**
Since there is no proxy setup on the node or on the go, the mod should get downloaded as any other packages on the node and run to completion

**Environment**
- airshipctl Version:  v0.1.0 (from Master)
- Operating System: Ubuntu 20.04 LTS
- Kernel version: 5.4.0-48-generic
- Kubernetes Version: N/A
- Go version:  go1.15.2 linux/amd64
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): VM (4 vCPU), 8GB RAM, 60GB HDD

**Comment by sirajyasin** [comment]
@bravinash82 , could you please let us know if you still have this issue. We do not see any hardcoded proxy in the scripts. So it might be from your environment variables or proxy settings in docker config. Kindly check your environment variables and try un-setting all proxy variables and re-retry. Let us know if you still have issues

**Comment by bravinash82** [comment]
I have double checked my environment for any proxies configured on the OS, APT, GO. There is none, in fact I can to a go get or a go download and they work just fine. Do you know any particular configuration I need to check?

**Comment by sirajyasin** [comment]
@bravinash82 , could you also please check your docker config for any proxy settings. Because from your Error Log, the proxy is used for `go mod download` within docker container.

> cat /etc/systemd/system/docker.service.d/http-proxy.conf
or
> systemctl show docker --property Environment

**Comment by bravinash82** [comment]
root@k8s:~# systemctl show docker --property Environment
**Environment=**
I am puzzled.

**Comment by bravinash82** [comment]
I think I found the problem:

root@k8s:~/community/airshipctl# docker image ls -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              898d7e626c5a        14 minutes ago      763MB
<none>              <none>              c3ac435905d4        14 minutes ago      763MB
<none>              <none>              642fcffc5670        14 minutes ago      763MB
<none>              <none>              f98a79482a17        14 minutes ago      763MB
<none>              <none>              50b7967b9e8d        14 minutes ago      763MB
<none>              <none>              a3c3ee30f5f8        14 minutes ago      763MB
golang              1.13.1-stretch      f8c4e1a86e6d        13 months ago       763MB
root@k8s:~/community/airshipctl# docker run f8c4e1a86e6d env
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ff4fb5c181f3
**https_proxy=http://one.proxy.att.com:8080**
NO_PROXY=localhost,127.0.0.1,localaddress,.localdomain.com,.localdomain.local,192.168.0.0/16,10.96.0.0/12,172.25.50.21,172.25.50.22,172.25.50.23,172.25.50.24
no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com,.localdomain.local,192.168.0.0/16,10.96.0.0/12,172.25.50.21,172.25.50.22,172.25.50.23,172.25.50.24
**HTTP_PROXY=http://one.proxy.att.com:8080
http_proxy=http://one.proxy.att.com:8080
HTTPS_PROXY=http://one.proxy.att.com:8080**
GOLANG_VERSION=1.13.1
GOPATH=/go
HOME=/root
root@k8s:~/community/airshipctl#


Looks like the golang image used by the Makefile is already set with the proxy in its environment!

**Comment by bravinash82** [comment]
Thanks, I fixed it, the proxy was actually configured in here "~/.docker/config.json". I cleared and it started working. You can close this bug now.
