### ISSUE TITLE
Update kubeconfig in manifests

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#375]
As an operator, I want the ability to inject a kubeconfig into the appropriate manifests, so that I can update/modify the kubeconfig for a cluster as needed.

The issue should provide the user command to specify a kubeconfig source & manifest location for the cluster to be updated. The specified kubeconfig is then updated in the manifests for appropriate cluster as needed. This may leverage a kubeconfig retrieved through #374 but is not dependent on this issue. 

Acceptance criteria:
Validate the kubeconfig has been updated once the command has been issued.

**Comment by ak3216** [comment]
This was created from the 10/19 YAML discussion

**Comment by sirajyasin** [comment]
I can start working on this issue if no one has started yet.

**Comment by sirajyasin** [comment]
@ak3216 
We already have a option to pass custom kubeconfig to the phase command. We are using that to specify the dynamic kubeconfig created during the deployment.

From our last discussion if i remember correct, we do not have to persist the dynamic kubeconfig into filesystem and it will be the responsibility of the DE to save it.

Please correct me if my understanding is wrong.

**Comment by ak3216** [comment]
@jezogwza @teoyaomiqui do we still need this issue? See Siraj's comment above. Thanks.

**Comment by teoyaomiqui** [comment]
@ak3216 i think this task can be closed as is. we have agreed at one of the design calls, that kubeconfig should have various sources instead of injection into kustomize.

So I would suggest that we close this one, and open new one

**Comment by ak3216** [comment]
Closing per comments & #460 will provide updated approach.
