### ISSUE TITLE
Define mechanism for managing lifecycle of Labels, Taints post deployment via BMH or provider artifacts

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#377]
The ability to update the BMH with some labels, that will be bubbled up to the Kubernetes nodes.

Watch for conflicts with CAPI managing labels, or other parties.
Might need to have specific prefixes to avoid race conditions.
Suggestion ...  is using **_Prefix Labels._**  And then automatically appending the prefix to any label this manages,

This is likely an extension to capm3.

This might belong within the context of a CAPI provider infrastructure object mechanism.

**Comment by Arvinderpal** [comment]
Ref metal3 issue: https://github.com/metal3-io/metal3-docs/issues/146

**Comment by ak3216** [comment]
this is different from #3 in that it's creating an operator independent of CAPI.

**Comment by Arvinderpal** [comment]
@ak3216 We are working out the details of the design. The proposal in meta3 and discussion can be found here: https://github.com/metal3-io/metal3-docs/pull/149

**Comment by Arvinderpal** [comment]
Update on this:
The design doc ready to merge. Waiting on lazy consensus by end of this week: https://github.com/metal3-io/metal3-docs/pull/149
The PR for the feature is also under review: https://github.com/metal3-io/cluster-api-provider-metal3/pull/152

**Comment by Arvinderpal** [comment]
Update: The design proposal was accepted and merged. The feature PR is currently under review.

**Comment by Arvinderpal** [comment]
This feature has landed in capm3: https://github.com/metal3-io/cluster-api-provider-metal3/pull/152

**Comment by eak13** [comment]
Closing per above.
