### ISSUE TITLE
GPG Sops integration issues with gate

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#378]
**Describe the bug**
The introduction of GPG Sops integration to handle secret encryption/decryption is now causing other patchsets to fail the gating tests at airship-airshipctl-lint-unit.

These are the patchsets causing the issue:
* https://review.opendev.org/#/c/758392
* https://review.opendev.org/#/c/758707

Example patchsets failing the gate:
* https://review.opendev.org/#/c/759763/
  * https://zuul.opendev.org/t/openstack/build/b232edc33e2943c1882e5016d32e263c
* https://review.opendev.org/#/c/757570/
  * https://zuul.opendev.org/t/openstack/build/dd7d1dbb8e1b4758ab15f19cb35c40f1/console

This issue is to provide temporary remediation to fix the gating issues with the current design & create mock tests to bypass these gpg issues.

**Comment by mf4716** [comment]
@cloudstarz - Uday, please ack. receipt, add comment, and we can add you as an assignee.

**Comment by cloudstarz** [comment]
Hey all, I am working on this right now. This is being a little tricky to investigate and is very flaky, but we believe an old gpg version is the culprit here and will keep this issue posted

**Comment by cloudstarz** [comment]
Work in progress patchset here: https://review.opendev.org/#/c/759918

**Comment by cloudstarz** [comment]
Created https://github.com/mozilla/sops/pull/762 to be able to better understand the underlying issues with sops even better. The patchset linked above fixes one bug with the key cleanup that ha scaused the Decrypt tests to fail in the above patchsets.

**Comment by teoyaomiqui** [comment]
related patchset https://github.com/airshipit/airshipctl/issues/378

**Comment by ak3216** [comment]
@teoyaomiqui with https://review.opendev.org/c/airship/airshipctl/+/761610/ getting merged, can we go ahead and close this issue out?

**Comment by teoyaomiqui** [comment]
@ak3216 I think so, yes

**Comment by ak3216** [comment]
Closing per code merge
