### ISSUE TITLE
Missing plugin images are handled as document errors

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#392]
**Describe the bug**
If a plugin image is missing, airshipctl will not halt and display an error; it will continue to attempt to process documents, causing misleading Kustomize errors.

```
[airshipctl] 2020/11/06 16:23:23 opendev.org/airship/airshipctl@/pkg/cluster/clustermap/map.go:61: cluster  is not defined in cluster map &{{ClusterMap airshipit.org/v1alpha1} {main-map      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[airshipit.org/deploy-k8s:false] map[] [] []  []} map[ephemeral-cluster:0xc0008d5b30 target-cluster:0xc0008d5b60]}
Unable to find image 'quay.io/airshipit/templater:dev' locally
docker: Error response from daemon: manifest for quay.io/airshipit/templater:dev not found: manifest unknown: manifest unknown.
See 'docker run --help'.
accumulating resources: accumulateFile "accumulating resources from '../catalogues': '/home/ubuntu/opendev.org/airship/treasuremap/manifests/site/test-site/ephemeral/catalogues' must resolve to a file", accumulateDirector: "recursed accumulation of path '/home/ubuntu/opendev.org/airship/treasuremap/manifests/site/test-site/ephemeral/catalogues': accumulating resources: accumulateFile \"accumulating resources from '../../target/catalogues': '/home/ubuntu/opendev.org/airship/treasuremap/manifests/site/test-site/target/catalogues' must resolve to a file\", accumulateDirector: \"recursed accumulation of path '/home/ubuntu/opendev.org/airship/treasuremap/manifests/site/test-site/target/catalogues': accumulating resources: accumulateFile \\\"accumulating resources from '../../../../type/airship-core/shared/catalogues': '/home/ubuntu/opendev.org/airship/treasuremap/manifests/type/airship-core/shared/catalogues' must resolve to a file\\\", accumulateDirector: \\\"recursed accumulation of path '/home/ubuntu/opendev.org/airship/treasuremap/manifests/type/airship-core/shared/catalogues': accumulating resources: accumulateFile \\\\\\\"accumulating resources from '../../../../../../airshipctl/manifests/function/airshipctl-base-catalogues': '/home/ubuntu/opendev.org/airship/airshipctl/manifests/function/airshipctl-base-catalogues' must resolve to a file\\\\\\\", accumulateDirector: \\\\\\\"recursed accumulation of path '/home/ubuntu/opendev.org/airship/airshipctl/manifests/function/airshipctl-base-catalogues': couldn't execute function: exit status 125\\\\\\\"\\\"\""
```

**Steps To Reproduce**
1. Remove local Docker images
2. Run `airshipctl phase run bootstrap`

**Expected behavior**
Airshipctl should produce a relevant, actionable error for the user. Something like "Plugin image `quay.io/airshipit/templater:dev` not found". Airshipctl should not show Kustomize errors when plugin images are missing.

**Comment by drewwalters96** [comment]
The output looks fairly clean above and does have a Docker error; however, in a terminal, it is easily missed by the last line wrapping several times. To a new user, it looks like a Kustomize error.

**Comment by teoyaomiqui** [comment]
@drewwalters96 I think that it is very important to save original kustomize error, it can help debugging.
Would it be better to wrap errors produced by plugins into ErrDocumentPluginRun{} that would embed kustomize error, and print it in more informational and human readable way?

**Comment by drewwalters96** [comment]
@teoyaomiqui What information does the user need to extract from the Kustomize error? Kustomize errors are helpful when the user has a document error, but I thought this particular Kustomize error happened only because the templater did not execute.

**Comment by vetbijaya** [comment]
I started working on this issue, trying to reproduce the error. Can someone assign this issue to me?

**Comment by teoyaomiqui** [comment]
@vetbijaya , @drewwalters96 I think this needs to be discussed more, I dont see this as bug.

We use kustomize to download image and run container as plugin, so this error is part of kustomize as expected. I dont think we can intervene in the middle of kustomize execution, the best we can do is to parse error message, and try to figure something out from there, and this isn't the best idea imho

**Comment by teoyaomiqui** [comment]
closing the issue, reopen if needed
