### ISSUE TITLE
Introduce "Phase Describe" Command

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#393]
**Proposed change**
Add an 'airshipctl phase describe' command that take a phase name/namespace and return information that would give an operator insight into what is contained within the phase.

The command should return:

1. A description of the phase.  This would require a description field be added to the Phase document that could be populated by the phase creator to provide useful information about the phase to a user.
2. A description of the executor used by the phase.  This would require the Executor interface to be extended with a method to retrieve its description.  Then the description of the executor associated to the specified phase could be retrieved.

**Comment by vetbijaya** [comment]
Please assign this issue to me.

**Comment by lb4368** [comment]
Per 12/1/20 design call, this command should be implemented by adding a yaml output option to the airshipctl phase list command from #358.  The command will output the phase artifacts in yaml output rather than tabular output.

Example:
airshipctl phase list -o yaml

**Comment by niharikabhavaraju** [comment]
please assign this to me

**Comment by ak3216** [comment]
@niharikabhavaraju you've been assigned as well.

**Comment by niharikabhavaraju** [comment]
changes related to this issue are made in #358 , PS:    https://review.opendev.org/c/airship/airshipctl/+/769392
and https://review.opendev.org/c/airship/airshipctl/+/769251

**Comment by niharikabhavaraju** [comment]
PS's related to this phase list -o yaml changes are made in #358  https://review.opendev.org/c/airship/airshipctl/+/769392 and https://review.opendev.org/c/airship/airshipctl/+/769251 , these PS's are merged. This issue can be closed.

**Comment by ak3216** [comment]
Closing per patchset merges
