### ISSUE TITLE
Enable AuthN module for OpenID Connect provider such as DEX in target Kubernetes cluster

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#4]
Authentication modules Kubernetes include Client Certificates, Password, and Plain Tokens, Bootstrap Tokens, and JWT Tokens (used for service accounts). Multiple authentication modules can be specified, in which case each one is tried in sequence, until one of them succeeds.

Target Kubernetes cluster, bootstrapped by airshipctl should be integrated with OpenID Connect Provider so that a user can be authenticated by the authentication back-end such as LDAP and github that are not directly supported by Kubernetes. OIDC provider sits between Kube api server and authentication back-ends to support authentication of users via LDAP etc.

OIDC provider is required to be deployed in the target cluster and be integrated with authentication back-ends.

Once the user is authenticated, Kubernetes RBAC mechanism can be used to authorize the users for what they are allowed / denied for.

DEX : https://github.com/dexidp/dex

- Decide whether DEX is infrastructure or software stack 
- Create mechanism to deliver DEX to the cluster . i.e. Helm Chart 
- Define  Armada Chart definition for DEX.
- Define how and when Kubernetes is configured with these authentication option

**Comment by ianpittwood** [comment]
@singhannie could we have further clarification on what the specific change/feature for airshipctl is? What's the end goal as far as expected behavior?

**Comment by lb4368** [comment]
Treasuremap issue (https://github.com/airshipit/treasuremap/issues/19) has been created to deliver Dex helm chart.  Do we still need this issue in airshipctl?

**Comment by drewwalters96** [comment]
@lb4368 I don't think so. Closing
