### ISSUE TITLE
Improve code documentation for godoc

### ISSUE THREAD

**Issue by ianpittwood** [airshipit/airshipctl#40]
Relates-To: #58

**Problem description (if applicable)**
Many functions are relatively undocumented in the airshipctl code base. Undocumented code can make it more difficult for developers to navigate code and efficiently work on enhancements and bug fixes.

**Proposed change**
We should improve function documentation to help improve the project's readability in its raw form and in godoc. There is an [official godoc guide](https://blog.golang.org/godoc-documenting-go-code), but it is rather incomplete. Luckily, there are some third party resources available such as [godoc-tricks](https://github.com/fluhus/godoc-tricks) that can help us create better code documentation.

**Comment by rezroo** [comment]
Please assign to me.

**Comment by ianpittwood** [comment]
All yours @rezroo

**Comment by muly** [comment]
@rezroo: question.. is there a patch set associated to this issue?

**Comment by rezroo** [comment]
@muly - I haven't had time to work on it, and don't see the situation improving.

**Comment by muly** [comment]
i'll pick this issue

**Comment by muly** [comment]
created https://review.opendev.org/#/c/742034/

**Comment by muly** [comment]
@drewwalters96 , the patchset is merged, how to close this issue?

**Comment by ak3216** [comment]
Code was merged on July 30. Closing.
