### ISSUE TITLE
Missing configuration for the virtual media process in ironic function

### ISSUE THREAD

**Issue by mel1nn** [airshipit/airshipctl#420]
When installing Ironic with airshipctl and provision a bare metal server using the virtualmedia process, an error occurs in the Ironic pod: The isolinux.bin file is not found.

We need to specify the path of this file in the ironic configuration as set in https://github.com/metal3-io/ironic-image/blob/168207c1c2bdfa8761269bdf6434883b05647036/ironic.conf.j2#L39: 

`isolinux_bin = /usr/share/syslinux/isolinux.bin`

Thanks !

**Comment by mattmceuen** [comment]
Thank you for submitting this, @mel1nn!

@sb464f, have you run across this issue in your testing?

This may be something we should bake into our custom ironic image, which is on the menu for next Tuesday's design meeting.

**Comment by mel1nn** [comment]
Yes and I fixed or by adding the file path of the isolinux_bin :)

**Comment by sb464f** [comment]
@mattmceuen we override the ironic conf in our manifests with this config -> https://opendev.org/airship/airshipctl/src/branch/master/manifests/function/baremetal-operator/config-file/ironic.conf

but in the ironic logs only this entry for isolinux_bin
`2020-11-23 20:34:05.542 11 DEBUG oslo_service.service [-] isolinux_bin                   = /usr/lib/syslinux/isolinux.bin log_opt_values /usr/lib/python3.6/site-packages/oslo_config/cfg.py:2585^[[00m
`

**Comment by mel1nn** [comment]
Yes, and this specified file is not available in the docker image.

**Comment by mattmceuen** [comment]
@mel1nn I see the reference to `/usr/lib/syslinux/isolinux.bin` in my ironic logs, but I don't see an error for some reason, even though I confirmed that the file isn't in that location on the ironic container.  However, it's also absent from my `/usr/share/syslinux`!  So a couple questions:

1. I'm not familiar with how this file is used by ironic; do you have any idea why it would _conditionally_ be required?  I.e. why might it be causing you an error and not me.
2. What ironic image are you using?  In my environment I have `quay.io/metal3-io/ironic:capm3-v0.4.0`

**Comment by mel1nn** [comment]
The error occurs only when you try to provision a baremetal host with the virtual media process.

And I use the latest ironic image `quay.io/metal3-io/ironic:latest`. In this image,  the `/usr/share/syslinux/isolinux.bin` is present !

**Comment by mel1nn** [comment]
An error also occurs on the server during the boot of the kernel image.

Finally, I have succeeded to do it by setting the latest docker images version of ironic (latest) and bare metal operator (v0.4.1) and by changing the ironic configuration following the one specified in the [metal3/ironic-image](https://github.com/metal3-io/ironic-image/blob/master/ironic.conf.j2) repository.

Thanks for your help.

**Comment by mattmceuen** [comment]
Glad to hear it's working for you with that configuration, thanks for reporting it back here @mel1nn.

**Comment by mel1nn** [comment]
I still have a question, why airship does not provide the same configuration for ironic than the one specified in the [metal3/ironic-image repository](https://github.com/metal3-io/ironic-image/blob/master/ironic.conf.j2) ?
