### ISSUE TITLE
Support tigera operator wait logic in airshipctl

### ISSUE THREAD

**Issue by seaneagan** [airshipit/airshipctl#443]
**Problem description (if applicable)**

In https://review.opendev.org/c/airship/airshipctl/+/762773/ custom wait logic was added to the gate scripts for the Tigera Operator, but in order for the [plan run](#395) functionality to work, the custom wait logic would need to be integrated into `airshipctl` itself. It seems this would be along the lines of ignoring certain resources (e.g. `installation`?), and adding custom wait rules to the cli-utils / kstatus integration in `airshipctl` targeting `tigerastatus` resources.

**Comment by seaneagan** [comment]
2/23 design call discussion:
* Use generic container phase to wait for all expected tigerastatus CRs to exist and be [Available](https://github.com/airshipit/airshipctl/blob/6f16a2e84052db732227290c53a8e2c78634fd4b/manifests/function/cni/tigera-operator/v1.13.0/upstream/tigera-operator.yaml#L4072).

We also have another potential race condition (though I haven't seen it triggered yet) in that we are including the 
installations.operator.tigera.io [CRD](https://github.com/airshipit/airshipctl/blob/6f16a2e84052db732227290c53a8e2c78634fd4b/manifests/function/cni/tigera-operator/v1.13.0/upstream/tigera-operator.yaml#L3276) and [CR](https://github.com/airshipit/airshipctl/blob/6f16a2e84052db732227290c53a8e2c78634fd4b/manifests/function/cni/tigera-operator/v1.13.0/custom-resources.yaml) in the same [function](https://github.com/airshipit/airshipctl/blob/6f16a2e84052db732227290c53a8e2c78634fd4b/manifests/function/cni/tigera-operator/v1.13.0/kustomization.yaml)/phase. We should split those into separate phases i.e. CRD phase, then CR.

**Comment by lb4368** [comment]
@sirajyasin @seaneagan   
Doesn't the implementation of the kubectl-wait-tigera GenericContainer executor used by the kubectl-wait-tigera-ephemeral/kubectl-wait-tigera-target phases in the PS above  (https://review.opendev.org/c/airship/airshipctl/+/784383) already account for the potential race condition?  See https://review.opendev.org/c/airship/airshipctl/+/784383/11/manifests/function/phase-helpers/wait_tigera/kubectl_wait_tigera.sh.

Do you think we can just close this issue?  Is there still some reason we need the CRD/CR in separate phases?

**Comment by sirajyasin** [comment]
@lb4368 , the issue mentioned in this Bug ( custom wait logic ) is addressed in the mentioned PS with Generic container. But we are still deploying the CR and CRD as part of the same phase "initinfra-networking". As @seaneagan mentioned it is always a good idea to separate CR and CRD into different phase to avoid any race condition. May be we can create a new issue ( enhancement ) to separate CR and CRD for tigera into different phases.

**Comment by seaneagan** [comment]
The race condition comes into play when deploying the CR before waiting for the CRD to be established. With this implementation we are explicitly waiting for the CRD to become ready first, so in this case there is no race condition. So personally I think putting them in the same phase is ok, however since they cannot be parallelized another phase should not really slow things down, so that would be fine too, but I think it is more of a matter of preference.

**Comment by lb4368** [comment]
Closing this issue based upon https://review.opendev.org/c/airship/airshipctl/+/784383.  If at some point there is a need/desire to split the tigerastatus CRD and CR into separate phases, a new issue can be created.
