### ISSUE TITLE
airshipctl config get-context should display the present context

### ISSUE THREAD

**Issue by sb1975** [airshipit/airshipctl#445]
**Describe the bug**
When we run the command to display present context using  `airshipctl config get-context`

We get the below:
```
$ sudo airshipctl config get-context
contextKubeconf: ""
managementConfiguration: default
manifest: default

contextKubeconf: ephemeral-cluster_ephemeral
managementConfiguration: dummy_management_config
manifest: treasuremap_ci

contextKubeconf: target-cluster_target
managementConfiguration: dummy_management_config
manifest: treasuremap_ci

```

Now a quick look into the config file we can see all the context.

```
$ sudo cat ~/.airship/config
apiVersion: airshipit.org/v1alpha1
contexts:
  default:
    contextKubeconf: ""
    managementConfiguration: default
    manifest: default
  ephemeral-cluster:
    contextKubeconf: ephemeral-cluster_ephemeral
    managementConfiguration: dummy_management_config
    manifest: treasuremap_ci
  target-cluster:
    contextKubeconf: target-cluster_target
    managementConfiguration: dummy_management_config
    manifest: treasuremap_ci
currentContext: ephemeral-cluster
...
```

**Steps To Reproduce**
Visible in any environment.

**Expected behavior**
Output of  `$ sudo airshipctl config get-context`
should be the current context like - ephemeral-cluster

**Comment by sirajyasin** [comment]
@sb1975
airshipctl config get-context => will display all available contexts
airshipctl config get-context **--current** => will display only current context information

So i assume it is working as expected. Please let us know if you still think it is an issue.

**Comment by drewwalters96** [comment]
From the flightplan, we can close this.
