### ISSUE TITLE
Error checking for cobra commands doesn't compare error messages

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#451]
**Describe the bug**
The `testutil.CmdTest` has an `Error` field which can be used to verify that a command produces an error. Currently, the test only asserts that an error was either returned or not, but disregards the message of the expected error.

**Expected behavior**
Tests should fail if the actual error message is different from the expected error message.

**Comment by uberscott** [comment]
Assign to me, please.

**Comment by ian-howell** [comment]
PS here: https://review.opendev.org/c/airship/airshipctl/+/774164
