### ISSUE TITLE
Prepare a secrets/encryption how-to-guide

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#454]
As an Airship 2.0 user, I want to have a guide for managing secrets, encryption & decryption via airshipctl, so that I can successfully perform the following:

- Basic encryption/decryption generation
- Inclusion in phase document sets
- Life-cycling secrets
- Best practices for grouping

Current patchsets (merged or otherwise) can be found here: https://review.opendev.org/q/topic:%22generator_sops_encrypter%22+(status:open%20OR%20status:merged)

**Comment by aodinokov** [comment]
@ak3216 I can stab the initial version on that guide.. Probably it will be the easiest for everyone if you assign it to me

**Comment by ak3216** [comment]
Thanks @aodinokov. Assigned #453 and this one to you. Happy to help in any way you need.

**Comment by SirishaGopigiri** [comment]
Hi
I think some part of the documentation is addressed in this PS: https://review.opendev.org/c/airship/airshipctl/+/772667
Please let me know your thoughts

**Comment by aodinokov** [comment]
Thank you @SirishaGopigiri !

here is some part that I've prepared https://docs.google.com/document/d/1d4hmwYVnvIWQnTVSezsni_VDVtduydapjUbGhU5CAMk/edit#heading=h.r49446441y20
as well. probably will need to combine everything together :)

**Comment by aodinokov** [comment]
First draft https://review.opendev.org/c/airship/airshipctl/+/774543

**Comment by aodinokov** [comment]
Updated (added more parts: encryption, troubleshooting)

**Comment by aodinokov** [comment]
this ^ has been merged and may be closed

**Comment by ak3216** [comment]
@aodinokov good deal. Thanks! Closing per code merge.
