### ISSUE TITLE
Third Party Gating log collection enhancements

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#462]
Enhance the third party gating log collection (implemented by #449) as follows:
•  Log collection URL is now printed at the end of Pipeline. Enhance the process to post the URL back to Gerrit when updating the Voting. 
•  Create configurable script to cleanup/archive the old logs based on the available space and/or time duration.

**Comment by sirajyasin** [comment]
@ak3216 , can you please assign this issue to me

**Comment by sirajyasin** [comment]
@ak3216 , This issue can be closed now. Both the tasks mentioned in the issue is implemented and working.

**Comment by ak3216** [comment]
Closing per @sirajyasin updates, verified links appearing in gerrit messages.
