### ISSUE TITLE
kind: Secret - Replacement transformer does not provide option to replace base64 encoded data

### ISSUE THREAD

**Issue by sshiba** [airshipit/airshipctl#470]
**Describe the bug**
Replacement transformer does not provide option to replace a certificate base64 encoded data for objects of `kind: Secret`.
It forces to assign non base64 encoded value, instead, which is not consistent with this object type, i.e., use the `data `field for base64 encoded values and use of `stringData `for _clear_ text data.
as it is hard-coded to encode any data prior to replacement. This behavior is different

**Steps To Reproduce**
Reference a base64 encoded certificate to replace and the encoded value will be re-encoded.

**Expected behavior**
A referenced base64 encoded certificate should be replaced as it is and not be re-encoded.

**Comment by aodinokov** [comment]
@sshiba , it provides( I just realized 1 day after our conversation):
if you use jsonpath syntax in fieldref it won't do base64. it will just copy the data.
Please try `"{.data}"` instead of `data`.

**Comment by ian-howell** [comment]
Tested this and I can confirm @aodinokov's suggestion. [Documentation already states to use jsonpath](https://github.com/airshipit/airshipctl/tree/master/krm-functions/replacement-transformer#configuration-file-format), so I'm going to go ahead and close this.
