### ISSUE TITLE
Introduce Validate() method to ClusterMap interface

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#481]
**Problem description (if applicable)**
A ClusterMap interface can have multiple clusters defined in it, but there is no validation.

Validation is a very important step for ClusterMap, because clusters define parent-child dependencies. We should develop Validate() interface that would, at minimum, make sure that no circular parent-child dependencies are introduced in it.

**Proposed change**
Develop Validate() method for pkg/cluster/clustermap.ClusterMap interface.

**Comment by gtsteffaniak** [comment]
please assign me this.
