### ISSUE TITLE
airshipctl remotedirect-ephemeral phase should have an option to wait 

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#483]
**Problem description**
The remotedirect-ephemeral phase defined in airshipctl baremetal deployment issues a baremetal remote-direct command but does not wait for the ephemeral node and cluster to be fully available.

**Proposed change**
Update the remotedirect-ephemeral phase/RemoteDirectEphemeral executor to allow waiting for the ephemeral node and cluster to be fully available.

This issue replaces #236.

**Comment by teoyaomiqui** [comment]
@lb4368 are you sure this belongs to V2 ?  I think we discussed at the flight plan that this is out of scope, but I am not sure on this one

**Comment by lb4368** [comment]
> 
> 
> @lb4368 are you sure this belongs to V2 ? I think we discussed at the flight plan that this is out of scope, but I am not sure on this one

@teoyaomiqui This is currently marked with the "Future" milestone for later design/implementation

**Comment by shon-phand** [comment]
Is this  still a valid issue? I can see we have GenericContainer/Phase-helpers in place to check if ephemeral node is running state and then only deployment proceeds further.  If not what should be the approach to tackle this issue.

**Comment by lb4368** [comment]
@shon-phand   I tend to agree.  This issue was written before the full phase plan was implemented with the GenericContainer phases to check that the ephemeral cluster is up and is probably out-of-date.  The only thing to consider would be if we would want the remote-direct task and check to be within the same phase, but I don't think this is necessary at this time.  I will go ahead and close this, and we can re-open in the future if necessary.
