### ISSUE TITLE
kubeconfig flag is no longer available in airshipctl

### ISSUE THREAD

**Issue by sureshl** [airshipit/airshipctl#486]
**Describe the bug**
airshiptcl command with kubeconfig option was working previously but now has stopped working and throws the below error message.
# airshipctl phase run clusterctl-init-ephemeral --debug --kubeconfig ${KUBECONFIG}
**unknown flag: --kubeconfig**

**Steps To Reproduce**
Execute the below command
# export KUBECONFIG="${HOME}/.airship/kubeconfig"
# airshipctl phase run clusterctl-init-ephemeral --debug --kubeconfig ${KUBECONFIG}

**Expected behavior**
airshipctl phase run with kubeconfig option should successfully complete as previously ?

**Environment**
- airshipctl Version: 
- Operating System: Ubuntu 18.04
- Kernel version: 5.4.0-1040-azure
- Kubernetes Version: v1.20.4
- Go version: "go1.15.5"
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): Standard D8s v3 (8 vcpus, 32 GiB memory)
-

**Comment by teoyaomiqui** [comment]
@sureshl we have removed the flag from the command, now it works only declaratively. If you want to use ur site specific kubeconfig, you must specify path to it in clustermap for the specific cluster, here is example. U can also simply put your kubeconfig to that lcoation

**Comment by rkjain** [comment]
@teoyaomiqui  can you share the example. I will test them with docker provider.

**Comment by teoyaomiqui** [comment]
@rkjain Really sorry, that I didn't paste it the first time, I actually thought I did. here is example:
https://github.com/airshipit/airshipctl/blob/master/manifests/phases/cluster-map.yaml#L9-L15

In this example , if you put ur kubeconfig to ~/.airship/config, it will pick it up from there. But keep in mind that you also need to specify context in that kubeconfig for the specific cluster.

**Comment by rkjain** [comment]
@teoyaomiqui Thank you. I will test it and let you know how it goes.

**Comment by rkjain** [comment]
This can be closed. The issue is no  longer valid.
