### ISSUE TITLE
Missing group, value, kind in rendering errors

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#487]
**Describe the bug**
```
accumulating resources: 2 errors occurred:
        * accumulateFile error: "accumulating resources from 'nodes': '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes' must resolve to a file"
        * accumulateDirector error: "recursed accumulation of path '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes': loading generator plugins: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from '../hostgenerator': '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/hostgenerator' must resolve to a file\"\n\t* accumulateDirector error: \"recursed accumulation of path '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/hostgenerator': no matches for OriginalId ~G_~V_~K|~X|~N; no matches for CurrentId ~G_~V_~K|~X|~N; failed to find unique target for patch ~G_~V_~K|\"\n\n"
  ```

**Steps To Reproduce**
1. Checkout patchset 3 of [this change](https://review.opendev.org/c/airship/treasuremap/+/780121)
2. Execute `airshipctl phase render workers-target` 

**Expected behavior**
If there is a rendering issue, airshipctl needs to provide more information about the patches that failed to apply. The error above is not specific enough to pinpoint where the issue is in the phase.

**Comment by raliev12** [comment]
@drewwalters96 The issue you described isn't related to rendering itself. To be able to render documents using an executor as source, airshipctl tries to create appropriate Executor object. To create it, airshipctl need to have a bundle object inside, and this bundle is formed by related phase's documentEntryPoint. So basically, NewBundle() function called, which throws an error from inner call of kustomizer.Run(). Render method of executor wasn't even called since Executor object wasn't created. Unfortunately, I believe output you observed is the maximum information that we can fetch from kustomize library. Kustomize output is difficult to debug, but it is what it is. The only thing that can be added to error output is the additional message like "an error has occurred while creating new bundle by %PATH".

**Comment by drewwalters96** [comment]
@raliev12 The error from Kustomize gives us a little bit more to go on, revealing where the faulty patches are. Is there anything we can do to show this via airshipctl?

```
Error: accumulating resources: accumulateFile "accumulating resources from 'nodes': '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes' must resolve to a file", accumulateDirector: "recursed accumulation of path '/home/ubuntu/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes': loading generator plugins: expected file with Go object code at: /home/ubuntu/airshipit.org/v1alpha1/versionscatalogue/VersionsCatalogue.so"
```

**Comment by raliev12** [comment]
@drewwalters96 The Kustomize output really depends on its version. What version of Kustomize do you have? 
For example, version 3.8.5 produces output you mentioned (uses kustomize api v.0.6.3):

`root@ubuntu-airship:~/src/treasuremap# kustomize version
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}
root@ubuntu-airship:~/src/treasuremap# kustomize build --enable_alpha_plugins /root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers
gpg: keybox '/tmp/pubring.kbx' created
gpg: /tmp/trustdb.gpg: trustdb created
gpg: key 3D16CEE4A27381B4: public key "SOPS Functional Tests Key 1 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: key 3D16CEE4A27381B4: secret key imported
gpg: key D8720D957C3D3074: public key "SOPS Functional Tests Key 2 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: key D8720D957C3D3074: secret key imported
gpg: key 3D16CEE4A27381B4: "SOPS Functional Tests Key 1 (https://github.com/mozilla/sops/) <secops@mozilla.com>" not changed
gpg: key D8720D957C3D3074: "SOPS Functional Tests Key 2 (https://github.com/mozilla/sops/) <secops@mozilla.com>" not changed
gpg: key 19F9B5DAEA91FF86: public key "SOPS Functional Tests Key 3 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: Total number processed: 5
gpg:               imported: 3
gpg:              unchanged: 2
gpg:       secret keys read: 2
gpg:   secret keys imported: 2
Error: accumulating resources: accumulateFile "accumulating resources from 'nodes': '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes' must resolve to a file", accumulateDirector: "recursed accumulation of path '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes': loading generator plugins: expected file with Go object code at: /tmp/airshipit.org/v1alpha1/versionscatalogue/VersionsCatalogue.so"
`

However, same Kustomize command but with version 4.0.5 (uses api v0.8.5):

`root@ubuntu-airship:~/src/treasuremap# ./kustomize version
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T20:53:03Z GoOs:linux GoArch:amd64}
root@ubuntu-airship:~/src/treasuremap# ./kustomize build --enable-alpha-plugins /root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers
gpg: keybox '/tmp/pubring.kbx' created
gpg: /tmp/trustdb.gpg: trustdb created
gpg: key 3D16CEE4A27381B4: public key "SOPS Functional Tests Key 1 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: key 3D16CEE4A27381B4: secret key imported
gpg: key D8720D957C3D3074: public key "SOPS Functional Tests Key 2 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: key D8720D957C3D3074: secret key imported
gpg: key 3D16CEE4A27381B4: "SOPS Functional Tests Key 1 (https://github.com/mozilla/sops/) <secops@mozilla.com>" not changed
gpg: key D8720D957C3D3074: "SOPS Functional Tests Key 2 (https://github.com/mozilla/sops/) <secops@mozilla.com>" not changed
gpg: key 19F9B5DAEA91FF86: public key "SOPS Functional Tests Key 3 (https://github.com/mozilla/sops/) <secops@mozilla.com>" imported
gpg: Total number processed: 5
gpg:               imported: 3
gpg:              unchanged: 2
gpg:       secret keys read: 2
gpg:   secret keys imported: 2
Error: accumulating resources: accumulation err='accumulating resources from 'nodes': '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes' must resolve to a file': recursed accumulation of path '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/nodes': loading generator plugins: accumulation err='accumulating resources from '../hostgenerator': '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/hostgenerator' must resolve to a file': recursed accumulation of path '/root/src/treasuremap/manifests/site/virtual-network-cloud/target/workers/hostgenerator': no matches for IdId ~G_~V_~K|~X|~N; failed to find unique target for patch ~G_~V_~K|`

No GVK either. Finally, the error output depends only on 2 things: api version (we use 0.7.2 currently) and how [options](https://github.com/kubernetes-sigs/kustomize/blob/api/v0.7.2/api/krusty/options.go#L15-L44) are configured. For example, Kustomize 3.8.5 has disabled kyaml support by default, but 4.0.5 it's always on. I believe our [options](https://github.com/airshipit/airshipctl/blob/master/pkg/document/bundle.go#L107-L116) are constructed properly. The only thing that could be changed is switching plugin loading options from BploUseStaticallyLinked to BploLoadFromFileSys (it will change the output a little bit), but I don't personally think that it does worth it.

**Comment by drewwalters96** [comment]
Ah I see. I had 3.8.5 (same as your example output above). That's disappointing, but seeing as though we're limited in this situation, I suppose we have no other choice than to close this issue. This might be a good item for our upcoming troubleshooting guide @abailey011.

Thanks @raliev12
