### ISSUE TITLE
Support linting on windows

### ISSUE THREAD

**Issue by aschiefe** [airshipit/airshipctl#49]
**Problem description (if applicable)**
Windows linting is currently broken:
```
C:\aic\airshipctl> make test
mkdir -p tools/bin
./tools/install_linter
+ tools_bin_dir=./tools
+ download_url=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
+ version=v1.21.0
+ curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
+ sh -s -- -b ./tools/bin v1.21.0
golangci/golangci-lint info checking GitHub for tag 'v1.21.0'
golangci/golangci-lint crit unable to find 'v1.21.0' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
+ printf 'Something went wrong while installing golangci-lint\n'
Something went wrong while installing golangci-lint
+ exit 1
make: *** [Makefile:159: tools/bin/golangci-lint] Error 1
```
**Proposed change**
update the install_linter script to include a way to pull in the golangci-lint.exe for windows

**Potential impacts**
Windows is not technically an officially supported target architecture, but this is a nice to have in case anyone else is falling on this

**Comment by ianpittwood** [comment]
This should preferably be done by someone that uses Windows for their dev environment.

**Comment by aschiefe** [comment]
This appears to have been caused by a conflict between cygwin curl and a windows based curl.  It works fine when I disabled the system curl and used the cygwin one.  This might just be a side note type o thing for those who are using windows.
