### ISSUE TITLE
Concrete example in  airship in a pod Readme 

### ISSUE THREAD

**Issue by geokal** [airshipit/airshipctl#493]
**Problem description (if applicable)**
Am new in airshipctl and because "**airship in a bottle**" would not play well, i was advised to try "**airship in a pod**" but i m trying to find some info on which container should i run the airshipctl

**Proposed change**
Maybe an example of `/root/.airship/config` would be nice as well a little more detailed guide on how to run airshipctl , from which container etc

**Comment by manojkva** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
@manojkva all yours. If you have a t-shirt size to add, just let us know. Thanks.

**Comment by manojkva** [comment]
Updated Readme.md in a related PS for https://github.com/airshipit/airshipctl/issues/477 which is closed. Could this too be closed.

**Comment by ak3216** [comment]
closing per above merge
