### ISSUE TITLE
Enhance KubeadmControlPlane in base function to support bare metal

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#507]
Our bare metal lab definition is currently redefining the contents of the KubeadmControlPlane resource at the site level:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/ephemeral/controlplane/patch_controlplane.yaml

This is not ideal, and will result in the definition being duplicated across various site definitions.  Instead we should do one of the following:

1. If the bare metal reference KubeadmControlPlane contents are fine for the general case (VMs, etc), then perhaps the contents can simply be backported to the base function definition.
2. If we need to have different content for VM vs bare metal (or for different kinds of bare metal deployments) then we could create different functions -- e.g. function/k8scontrol (for real labs) + function/k8scontrol-vm (for VMs) or something

Either way, the base definition should allow for substitution of the site-specific values like IP addresses, which the k8scontrol function has today.

**Comment by mattmceuen** [comment]
Note that after updating the function, both of these patches should be removed:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/ephemeral/controlplane/patch_controlplane.yaml
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/target/controlplane/patch_controlplane.yaml

**Comment by sirajyasin** [comment]
The Site specific STL3 PSs referenced in the description is obsolete, and all of the site-level patching was removed in the final reference site PS[0]. I've confirmed with @imarijitbose. Looks like there is not any work on this issue at this point.
[0] https://review.opendev.org/c/airship/treasuremap/+/784619

@mattmceuen , could you please suggest if we can close this issue ?

**Comment by mattmceuen** [comment]
No work to do (it's already done) - closing
