### ISSUE TITLE
 Enhance ironic-entrypoints ConfigMap in base function to support bare metal

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#508]
Our bare metal lab definition is currently redefining the contents of the ironic-entrypoints resource at the site level:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/ephemeral/initinfra/ironic_entry.yaml

This is not ideal, and will result in the definition being duplicated across various site definitions. Instead we should do one of the following:

1. If the bare metal reference ironic-entrypoint contents are fine for the general case (VMs, etc), then perhaps the contents can simply be backported to the base function definition (baremetal-operator)
2. If we need to have different content for VM vs bare metal (or for different kinds of bare metal deployments) then we could create different functions -- e.g. function/baremetal-operator (for real labs) + function/baremetal-operator-vm (for VMs) or something

Either way, the base definition should allow for substitution of the site-specific value (but I don't spot any in the definition now).

**Comment by vetbijaya** [comment]
I can give a try to this one. Can someone assign this to me?

**Comment by mattmceuen** [comment]
Looks like this is no longer needed -- the latest STL3 manifests no longer have an ironic_entry.yaml, and instead are using the current airshipctl version defined in the baremetal-operator function.  Closing this issue.
