### ISSUE TITLE
Enhance base ironic-vars & deployment to support bare metal

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#509]
Our bare metal lab definition is currently redefining the contents of the ironic-vars ConfigMap at the site level:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/target/initinfra/patch_bmo_config.yaml
Likewise for the ironic deployment:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/target/initinfra/patch_ironic.yaml

This is not ideal, and will result in the definition being duplicated across various site definitions. Instead we should do one of the following:

1. If the bare metal reference ironic-vars contents are fine for the general case (VMs, etc), then perhaps the contents can simply be backported to the base function definition.
2. If we need to have different content for VM vs bare metal (or for different kinds of bare metal deployments) then we could create different functions -- e.g. function/baremetal-operator (for real labs) + function/baremetal-operator-vm (for VMs) or something

Either way, the base definition should allow for substitution of the site-specific values like IP addresses, which the baremetal-operator function has today.

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
@matthew-fuller all yours

**Comment by matthew-fuller** [comment]
This issue doesn't appear to be necessary anymore. The PS referenced in the description is obsolete, and all of the site-level patching was removed in the final reference site PS[0]. I've confirmed with @imarijitbose that there's no further work for this issue, but I'm placing it in Ready for Review in case @mattmceuen or anyone else wants to weigh in.

[0] https://review.opendev.org/c/airship/treasuremap/+/784619

**Comment by mattmceuen** [comment]
Looks good to me, glad we got all of this one taken care of and into the v2.0 release.  Thanks, closing this.
