### ISSUE TITLE
Using config set-context does not set context

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#51]
**Describe the bug**
Executing `airshipctl config set-context [context]` does not change the context, despite outputting a message saying the context was modified.

**Steps To Reproduce**
```
$ ./bin/airshipctl config get-context
Context: default
context-kubeconf: default_target

LocationOfOrigin: /home/ubuntu/.airship/kubeconfig
cluster: default_target
user: admin
```

```
$ ./bin/airshipctl config set-context default
Context "default" modified.
```

```
$ ./bin/airshipctl document pull
Missing configuration: Current Context is not defined
```

```
$ cat ~/.airship/config
apiVersion: airshipit.org/v1alpha1
clusters:
  default:
    cluster-type:
      target:
        bootstrap-info: ""
        cluster-kubeconf: default_target
contexts:
  default:
    context-kubeconf: default_target
current-context: ""
kind: Config
manifests:
  default:
    repository:
      checkout:
        branch: master
        commit-hash: master
        force: false
        remote-ref: master
        tag: ""
      url: https://opendev.org/airship/treasuremap
    target-path: /tmp/default
modules-config:
  bootstrapInfo:
    default:
      builder:
        networkConfigFileName: network-config
        outputMetadataFileName: output-metadata.yaml
        userDataFileName: user-data
      container:
        containerRuntime: docker
        image: quay.io/airshipit/isogen:latest
        volume: /srv/iso:/config
      remoteDirect:
        isoUrl: http://localhost:8099/debian-custom.iso
        remoteType: redfish
users:
  admin: {}
```

**Expected behavior**
Using `airshipctl set-context [context]` should change the current context.

**Environment**
- airshipctl Version: `v0.1.0`
- Operating System: Ubuntu 16.04.6 LTS (Xenial Xerus)
- Kernel version: `4.4.0-173-generic`
- Kubernetes Version: *none*
- Go version: `1.13.7`
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM): 4vCPUs, 24GB RAM, VM

**Comment by drewwalters96** [comment]
I'll just start looking into this one myself

**Comment by ian-howell** [comment]
Current behavior is working as intended, although I agree that it is very much nonintuitive. To change the `current-context` field, a user should run the command

```
airshipctl config set-context --current-context my-preferred-context
```

I'm not sure how much work you've done so far, but I'd propose the removal of the `--current-context` flag and replace it with a new sub-command `use-context`. This is not only more natural, but it also matches the behavior of `kubectl`.

**Comment by ian-howell** [comment]
There's probably value in using the `--current-context` flag in the same way that `kubectl` uses the `--current` flag, but that may be out of the scope of this change.

**Comment by drewwalters96** [comment]
@ian-howell I like the approach of a --use-context flag. The change to set the context when no flags are provided is on Gerrit: https://review.opendev.org/708479

I'll start working on replacing the --current-context flag, but I'll leave the original change alone in case there's value to putting it in now.

**Comment by ianpittwood** [comment]
@drewwalters96 is there additional work you're going to do under this issue?

**Comment by drewwalters96** [comment]
@ianpittwood I will create a new one and link it. For now, the unexpected behavior has been addressed.
