### ISSUE TITLE
Enhance KubeadmConfigTemplate in base function to support bare metal 

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#510]
Our bare metal lab definition is currently redefining the contents of the KubeadmConfigTemplate resource at the site level:
https://review.opendev.org/c/airship/treasuremap/+/772737/25/manifests/site/stl3-site/target/workers/kubeadmconfigtemplate.yaml

This is not ideal, and will result in the definition being duplicated across various site definitions. Instead we should do one of the following:

1. If the bare metal reference KubeadmConfigTemplate contents are fine for the general case (VMs, etc), then perhaps the contents can simply be backported to the base function definition.
2. If we need to have different content for VM vs bare metal (or for different kinds of bare metal deployments) then we could create different functions -- e.g. function/workers-capm3 (for real labs) + function/workers-camp3-vm (for VMs) or something

Either way, the base definition should allow for substitution of the site-specific values like IP addresses, which the workers-capm3 function has today.

NOTE:  the workers-capm3 function only exists in patchset form; it needs to merge before this enhancement can be done.
https://review.opendev.org/c/airship/airshipctl/+/778931

**Comment by mattmceuen** [comment]
Hey @sirajyasin I agree with you on both counts.  The /provision change is cosmetic, and better to err on the side of simplicity. And now that there's a workers-capm3 in airshipctl, a followon step will be to remove the treasuremap version of the function and configure treasuremap types to use the Airship version.  MattF and Manoj are both aware of this plan and anticipating it.

**Comment by gtsteffaniak** [comment]
Please assign to me

**Comment by mattmceuen** [comment]
This issue is still valid, looks like there are duplicate `workers-capm3` functions in both airshipctl and treasuremap.  @gtsteffaniak how is this looking; are they one-to-one?

**Comment by gtsteffaniak** [comment]
@mattmceuen  https://review.opendev.org/c/airship/treasuremap/+/800067 is waiting on feedback and reviews.

**Comment by lb4368** [comment]
Patchsets https://review.opendev.org/c/airship/treasuremap/+/800067 and https://review.opendev.org/c/airship/treasuremap/+/808807 merged
