### ISSUE TITLE
Enhance ReplacementTranformer to Allow Replacing into Multiple Targets

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#520]
**Problem description**
There are use cases where we need to ReplacementTransform the same source data into multiple target paths – e.g. replacing an IP address into many network policy rules. It would be helpful for the RT to support this natively.

**Proposed change**
Enhance the ReplacementTransformer KRM function to support specifying multiple targets so that a single source can be replaced into multiple targets.   

Improve Transformer to support Target as Slice : https://github.com/airshipit/airshipctl/blob/7998615a7b5847c367c29874641c8422157ebb52/pkg/document/plugin/replacement/transformer.go#L77

**Comment by sirajyasin** [comment]
I can start working on this issue if no one has started yet. @lb4368 can you please assign this issue to me

**Comment by lb4368** [comment]
@sirajyasin Done.  Thanks!

**Comment by aodinokov** [comment]
https://review.opendev.org/c/airship/airshipctl/+/788405 - merged, can be closed

**Comment by ak3216** [comment]
Closing per code merge above.
