### ISSUE TITLE
Merge v2.0 Branch Updates

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#538]
There are several patchsets that have merged to v2.0 branch that should be merged into master as needed.  

https://review.opendev.org/c/airship/airshipctl/+/786498
​https://review.opendev.org/c/airship/airshipctl/+/785914
​https://review.opendev.org/c/airship/airshipctl/+/786068
​https://review.opendev.org/c/airship/airshipctl/+/785943
​https://review.opendev.org/c/airship/airshipctl/+/785256

**Comment by sirajyasin** [comment]
I can start working on this issue. Please assign this to me

**Comment by sirajyasin** [comment]
https://review.opendev.org/c/airship/airshipctl/+/786498 => This change is applied as part of this PS (https://review.opendev.org/c/airship/airshipctl/+/785260), Cherry pick not required.
https://review.opendev.org/c/airship/airshipctl/+/785914 => Cherry picked to master and pending merge 
https://review.opendev.org/c/airship/airshipctl/+/786068 => Cherry picked to master and merged
https://review.opendev.org/c/airship/airshipctl/+/785943 => Cherry picked to master and merged
https://review.opendev.org/c/airship/airshipctl/+/785256 => Cherry picked to master and merged

**Comment by sirajyasin** [comment]
@lb4368 , All the above mentioned PSs are cherry picked from v2.0 to master and merged. I also double checked if there are any more PSs that needs to be cherry picked from V2.0, nothing other than these identified. This issue can be marked closed.

**Comment by lb4368** [comment]
Thanks @sirajyasin.  Closing.
