### ISSUE TITLE
Generic container timeout validation & enforcement

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#545]
Building on #544, provide a compliance mechanism to validate the timeout has been acknowledged & action has been taken.

**Comment by manojkva** [comment]
I could take this up.

**Comment by ak3216** [comment]
@manojkva all yours. Thanks.

**Comment by gtsteffaniak** [comment]
assign to me please

**Comment by raliev12** [comment]
Per Slack discussion, please assign this issue to me for finalizing.
