### ISSUE TITLE
Add replacements for `composite/infra`

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#549]
As it stands today:
* the cert-manager function doesn't specify any `/replacements`
* the tigera-operator function has `/replacements`, but they're not getting used anywhere afaict

In order to ensure proper replacement of container image refs, this story is to implement the following:
1. add the three images used in the cert-manager function to `airshipctl-base-catalogues/airshipctl-versions.yaml`.  
2. there is a single cert-manager entry in that catalogue already, which looks to be unneeded and should be removed.  The existing field is referenced by a mapping rule in `function/clusterctl/replacements`, which is no longer relevant and should be removed.
3. add a `cert-manager/v1.1.0/replacements` kustomization, which allows replacement of cert-manager container images from the versions catalogue
4. create a `composite/infra/replacements` entrypoint which aggregates the cert-manager replacements and the tigera-operator replacements
5. anywhere the `composite/infra` is referenced, in airshipctl or treasuremap, make sure the new `composite/infra/replacements` is pulled in as appropriate.  At the type level, that probably means referencing the new replacements in `initinfra/replacements`.  If there is a `test-site` site-level reference to `composite/infra` in airshipctl, then the replacements should be applied in that same kustomization.yaml.

**Comment by sirajyasin** [comment]
I can start working on this issue. can someone assign this to me
