### ISSUE TITLE
Upgrade Kubernetes from v1.18.6 to v1.20 for Bare Metal

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#555]
Airship 2 currently supports Kubernetes version 1.18.6. It is failing some of the Anuket conformance testing which requires a higher version.  Recommend upgrading Kubernetes to the v1.20 release for the bare metal instance of Airshipctl.

Release Announcement: https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/
v1.20 Change Log: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md
Release page: https://github.com/kubernetes/kubernetes/releases/

**Comment by hem2** [comment]
I can work on this. Can someone assign it to me?

**Comment by ak3216** [comment]
The plan is to pause on this & shift to v1.21 k8s upgrade which will be tracked under #589

**Comment by ak3216** [comment]
Closing this issue as we'll be upgrading to v1.21 & taking a slightly different implementation approach outlined in #589
