### ISSUE TITLE
Run Airship Certified Kubernetes conformance status against k8s 1.20

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#556]
Issue #555 is for upgrading k8s to v1.20.  However, there may be value in upgrading to v1.20 in the meantime, for the sake of Kubernetes Conformance.  This story can be implemented if we think #555 needs to wait till later.

Airship has passed its certification tests against the v1.18 version of the tests, and we've learned from the CNCF that our ability to use this as justification for saying "Airship is Certified" has already expired.  To re-gain conformance we need to resubmit with a newer version of k8s.

This issue is to both upgrade the Airship 2 docker instance of k8s to v1.20, as well as successfully run the conformance test suite and provide results to the OIF to submit to the CNCF.

More info on the scheduling / expiration:

As stated in Certified Kubernetes Conformance Program – Terms and Conditions, a
Participant’s permission to use the Certified Kubernetes Marks and Participant
Kubernetes Combinations with its Qualifying Offerings is time-limited. The
Certified Kubernetes Marks and Participant Kubernetes Combinations may be used
with a Qualifying Offering for a particular version of Kubernetes (e.g.,
Kubernetes x.y) until the later of:
* 12 months after the release date of Kubernetes x.y, or
* 9 months after the release date of the next minor release (e.g., Kubernetes
x.y+1)
v1.18.0 was released on March 25, 2020
https://github.com/kubernetes/kubernetes/releases/tag/v1.18.0
v1.19.0 was released on August 26, 2020
https://github.com/kubernetes/kubernetes/releases/tag/v1.19.0
Therefore, the expiration date for v1.18 is May 26, 2021.

**Comment by rkjain** [comment]
I can take this, and generate the results with docker provider as we did earlier.

**Comment by jezogwza** [comment]
Depends on. #555  and should fast follow with  Certification against 1.20. This should buy us certification until around Dec 2021 or so.

**Comment by ak3216** [comment]
The plan is to pause on the upgrade to v1.20 & shift to v1.21 k8s upgrade which will be tracked under #589. Believe the work to date on this issue has provided a Docker k8s v1.19 version which was needed to bring conformance current.

**Comment by ak3216** [comment]
@rkjain we've taken this one as far as it needs for now, correct? We got the CNCF compliance via v1.19 upgrade. If that's the case, thinking we can go ahead & close this one & use #589 to track the v1.21 k8s upgrade. Please let me know if you feel different. Thanks.

**Comment by rkjain** [comment]
@ak3216 Yes. I agree. We can close this and use #589 to track the v1.21 k8s upgrade

**Comment by ak3216** [comment]
Closing as the purpose of this issue has been met & will track the v1.21 k8s upgrade via #589
