### ISSUE TITLE
Upgrade sonobuoy to v0.51

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#557]
To provide additional automated testing support for Airship 2, we need to upgrade Sonobuoy from v0.18.2 to v0.51. 

From the Sonobuoy release notes, this is an incremental release, but utilizes a new release numbering schema.
https://sonobuoy.io/sonobuoy-v0-50/
Previously the Sonobuoy version number was coupled with the Kubernetes release number. As part of the march toward version v1.0, we decided to break that incremental versioning scheme and decouple our releases from that of Kubernetes release cadence. To amplify this effort, we have decided to reset our release number scheme going from v0.20 to v0.51 to ensure that there is no perceived relation between a Sonobuoy release and a Kubernetes release. This is because all Sonobuoy binaries will support most Kubernetes releases.

**Comment by ak3216** [comment]
Patchset https://review.opendev.org/c/airship/airshipctl/+/782614
@rkjain please comment so I can assign you. Thanks!

**Comment by rkjain** [comment]
I will take the issue. Thank you :)

**Comment by eak13** [comment]
Closing per above
