### ISSUE TITLE
Align other site definitions to use plans (and fix the failing docker gate)

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#564]
Issue #517 adjusted the test-site site definition to run deployments via phase plans, and deleted the per-phase scripts accordingly.

However, the other site definitions still need to be updated accordingly.  One practical issue demonstrated by this is that the (non-voting) docker-test-site gate is failing, because its zuul config points at the deleted scripts.

**Comment by eratnch** [comment]
Please assign to me.

**Comment by eratnch** [comment]
With the deletion of per-phase scripts, the deployment of each provider test sites needs to be adjusted/validated. I think it would be better to split this issue into multiple issues for tracking.
 
This issue #564 can be tracked for fixing CAPD deployment/zuul failures.
Similarly, 3 separate issues can be created as below:

- Fix/test CAPG test-site to switch to phasePlan
- Fix/test AZ test-site to switch to phasePlan
- Fix/test CAPO test-site to switch to phasePlan

Thanks.

**Comment by lb4368** [comment]
@eratnch Below are hackmd notes from today's Flight Plan call related to this issue.  From this design the first step seems to be to build the base phase plans.yaml for all providers into the `gating` type that the test-site can eventually patch.  Based upon this design would you still think we need separate issues per provider?   

`Normalize the phase plans across the different airshipctl sites, by setting up the same site-type inheritance for the phases entrypoint as already exists for test-site. The default phase plan in the gating type should be suitable for the general case – i.e. everything besides bare metal deployments (which have their own phases). At the e.g. docker site level, it can just consume those phase plans & use them; at the test-site level it’ll need to patch the plan to have all the bare metal phases as it has today.`

**Comment by eratnch** [comment]
This issue can be closed. Fix for this issue is merged.
