### ISSUE TITLE
Add --current flag to set-context subcommand

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#57]
**Problem description (if applicable)**
This is in response to #51. Right now, users must specify a context when executing `airshipctl set-context`. A user should be able to change context options for the current context without specifying its name by executing `airshipctl config set-context --current --manifest foo`.

**Proposed change**
Add the `--current` flag to the `set-context` subcommand of the config command.

**Potential impacts**
No potential security or performance related impacts anticipated.

**Comment by sirajyasin** [comment]
If no one have started working on this, I can start looking into this change.

**Comment by ian-howell** [comment]
@sirajyasin it's all yours

**Comment by sirajyasin** [comment]
Pushed PS for [Gerrit ](https://review.opendev.org/#/c/709142/) review

**Comment by sirajyasin** [comment]
The [PS ](https://review.opendev.org/#/c/709142/)is merged, it can be marked closed now
