### ISSUE TITLE
Upgrade Kubernetes from v1.18 to v1.20 for GCP

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#570]
As part of the Airshipctl kubernetes v1.18 to v1.20 upgrade outlined in issue #555, upgrade Kubernetes to v1.20 for the Google Cloud Platform (GCP).

**Comment by DannyMassa** [comment]
Assign to me please.

**Comment by ak3216** [comment]
The plan is to pause on this & shift to v1.21 k8s upgrade which will be tracked under #589

**Comment by DannyMassa** [comment]
@ak3216 Since priorities have changed, can I be absolved of this?

**Comment by ak3216** [comment]
Closing this issue as we'll be upgrading to v1.21 & taking a slightly different implementation approach outlined in #589
