### ISSUE TITLE
Upgrade Kubernetes from v1.18 to v1.20 for Openstack

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#571]
As part of the Airshipctl kubernetes v1.18 to v1.20 upgrade outlined in issue #555, upgrade Kubernetes to v1.20 for the Openstack provider.

**Comment by hem2** [comment]
@ak3216 , can you assign this to me? Thanks.

**Comment by hem2** [comment]
PS: https://review.opendev.org/c/airship/airshipctl/+/798032

**Comment by hem2** [comment]
Tested with CAPO v0.3.1, Ubuntu 20.04 (build server and ephemeral and target cluster) and K8S 1.20.7

**Comment by ak3216** [comment]
The plan is to pause on this & shift to v1.21 k8s upgrade which will be tracked under #589

**Comment by ak3216** [comment]
Closing this issue as we'll be upgrading to v1.21 & taking a slightly different implementation approach outlined in #589
