### ISSUE TITLE
Allow for image replacement in the iso-build-image executor

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#572]
We need the ability to override/replace the image parameter value in the the iso-build-image executor. It's currently a static value & common to all phases but needs to be a variable. 
https://opendev.org/airship/airshipctl/src/branch/master/manifests/phases/executors.yaml#L252

Tasks:
1. Create the image replacement transformer
2. Add the replacement reference to phases/kustomization.yaml 
3. Add the override value to the airshipctl versions catalogue

**Comment by pallavgupta** [comment]
I can look into this issue. Pls assign it to me.

**Comment by pallavgupta** [comment]
https://review.opendev.org/c/airship/airshipctl/+/795713
