### ISSUE TITLE
Generate additional CRDs for validation of airshipctl API types

### ISSUE THREAD

**Issue by seaneagan** [airshipit/airshipctl#574]
**Problem description (if applicable)**

As per #573  `make manifests` is currently trying to generate manifests for several api types which are beyone network/version catalogues that we have not actually committed to the repo yet. If we could fix the issues with those, perhaps they could be used to validate e.g. krm function configs (replacement transformer, templater, etc) as well as "config bundle" types (phases, phase plans, clustermaps, etc).

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by matthew-fuller** [comment]
Not sure why the bot didn't pick this one up, but here's the PS related to this issue: https://review.opendev.org/c/airship/airshipctl/+/797358
