### ISSUE TITLE
Fully Implement `gating` Type for Use By All Provider Types

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#575]
**Problem description**
In #564 work will be done to create a normalized phase plan for all provider types in the `gating` type.  Need to build out the rest of the type so that common entrypoints and manifests are managed at a common type level.

**Proposed change**
Make the `gating` type a fully-fledged type by moving the meat of the phase payload entrypoints from the site level to the type level. The site-level phase payload entrypoints will be very skinny after this (just like in treasuremap), making only the tweaks that are needed to tune the phase payloads per-provider.

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by matthew-fuller** [comment]
https://review.opendev.org/c/airship/airshipctl/+/799902
