### ISSUE TITLE
SOPS GPG Key Management

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#586]
**Problem description**
We currently do not have a robust solution for storing & managing the SOPS GPG keys that are used for encryption & decryption within Airship. Current downstream implementations involve generating & storing secrets through Jenkins pipelines and are less than ideal. 

**Proposed change**
Define an integration solution to provide GPG key management. It should be a system that provides certain capabilities like  secure key storage, role based access control (RBAC), key distribution, mutating admission control and/or controller that injects keys as needed.

One of the main options include Vault: 
https://www.vaultproject.io/docs/platform/k8s 
https://github.com/hashicorp/vault-k8s

While this issue may also be used to implement, the main purpose is to provide the design & approach for GPG key management.

**Potential impacts**
Need to ensure that encryption keys are securely stored and only accessible by authorized personnel.

**Comment by aodinokov** [comment]
I can work on it

**Comment by aodinokov** [comment]
I've demonstrated the approach on the design call. now this PR is ready for review: https://review.opendev.org/c/airship/airshipctl/+/806992
