### ISSUE TITLE
Remove airshipctl secret command

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#588]
**Problem description (if applicable)**
With the move to executing encryption via SOPS through phases, the airshipctl secret generate command is no longer needed & should be abandoned. Also, there are two cluster sub-commands: rotate-sa-token & check-expiration which are also deprecated & are non-functioning.

**Proposed change**
Remove the airshipctl secret generate command and the rotate-sa-token & check expiration cluster sub-commands. DO NOT remove the cluster command itself.

**Comment by raliev12** [comment]
@ak3216 please assign this one to me.

**Comment by ak3216** [comment]
@raliev12 done. Thanks!

**Comment by raliev12** [comment]
@ak3216 all the related commits were merged. The issue can be closed.

**Comment by ak3216** [comment]
Closing per merges.
