### ISSUE TITLE
Kubernetes uplift to v1.21 & Establish general pattern for K8s upgrades

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#589]
**Problem description**
Kubernetes has a cadence of posting a new release every 3 to 6 months. A release has roughly a 12 - 14 month lifespan. To maintain CNCF certification, conformance (like Anuket)  & currency with the latest releases, Airship needs to establish an ongoing cadence to continually uplift the supported Kubernetes version. 

v1.21 was released for GA on 5/12/2021. While there are current efforts underway to uplift to v1.20 (#555, #556, #569, #570, #571), we want to shift to v1.21 for Airship v2.1. Ideally, with the v1.21 uplift, we establish a more general pattern of Kubernetes upgrades where we are not necessarily focusing on the individual providers. 

K8s release information can be found here: https://kubernetes.io/releases/

**Tasks**
* Determine more general approach for k8s upgrade (design call topic - see notes). 
* Ensure image builder images reflect v1.21
* Using this approach, uplift the k8s version to v1.21 for:
    * Bare Metal - First priority
    * Azure - First priority
    * Docker - First priority
    * GCP - Second priority
    * Openstack  - Second priority

**Comment by ak3216** [comment]
Discussion of approach from 7/15 design call:
- Follow the release notes to identify any potential changes, incorporate in the uplift - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md
- Update common versions yaml to v1.21.2 - https://github.com/airshipit/airshipctl/blob/master/manifests/function/airshipctl-base-catalogues/versions-airshipctl.yaml
- Run validate docs  to lint the documents to ensure nothing breaks

Providers:
- Work backwards to the providers to ensure compatibility
- Determine if we need to upgrade the CAPI provider to support the K8s upgrade? Hopefully decoupled events, but may be some dependencies
- Use catalog overrides if issues with v1.21 or not supported

**Comment by diwrajchitoor** [comment]
Can someone assign this to me

**Comment by eak13** [comment]
https://review.opendev.org/c/airship/image-builder/+/812013/ merged
