### ISSUE TITLE
Add Tigera Installation Registry to Versions Catalogue Schema

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#590]
**Problem description (if applicable)**
The Tigera Operator includes a [document](https://github.com/airshipit/airshipctl/blob/16da661959b69ae54be83266cf7db0920083a2d4/manifests/function/cni/tigera-operator/v1.15.0/custom-resources.yaml) of `kind: Installation` that allows users to change the location of the container image repository used for deployment of Tigera images. This pattern does not fit our versions catalogue schema because we typically specify the location of each image individually rather than a repository that contains all of the images a particular operator will use.

**Proposed change**
We should include a new section in the versions catalogue schema, similar to the helm repository section, that allows us to catalogue container image repositories.

**Comment by shon-phand** [comment]
I can start working on this issue, please assign it to me

**Comment by shon-phand** [comment]
https://review.opendev.org/c/airship/airshipctl/+/798942
