### ISSUE TITLE
Clean up documentation for Airshipctl & CAPG integration

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#591]
**Problem description**
As changes have occurred in the Airship deployment process as it relates to GCP, the documentation has not been kept up to date. 
https://docs.airshipit.org/airshipctl/providers/cluster_api_gcp.html

**Tasks:**
- Review the CAPG documentation while working through the deployment process
- Make any updates to the documentation md
- Push the update to the website (which will happen automatically upon merge).

**Comment by DannyMassa** [comment]
Assign to me plz.
