### ISSUE TITLE
Remove unused patch_bmo_config.yaml

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/airshipctl#592]
There is a leftover patch_bmo_config.yaml in the airshipctl manifests; it used to be used but no longer appears to be.

This issue is to
1. identify the phase the file lives in
2. render the phase, and save the output for later comparison
3. delete the file
4. rerender the phase, and save the output
5. diff the pre-change and post-change outputs to confirm the deletion had no effect

This issue is earmarked for Eduardo.

**Comment by EduardoRivera96** [comment]
I will be picking up this issue.

**Comment by sirajyasin** [comment]
PS https://review.opendev.org/c/airship/airshipctl/+/810265
Validation steps:
 1) ./airshipctl phase render initinfra-target > initinfra-target.yaml
 2) rm manifests/site/test-site/target/initinfra/patch_bmo_config.yaml
 3) ./airshipctl phase render initinfra-target > initinfra-target_without_bmo_patch.yaml

4) Check Diff of rendered files before and after deleting patch_bmo_config.yaml

	airship@airship:~/airshipctl$ diff initinfra-target.yaml initinfra-target_without_bmo_patch.yaml
	airship@airship:~/airshipctl$

Patching ProvisioningIP is taken care with the mentioned replacement transformer.

manifests/function/airshipctl-base-catalogues/networking.yaml:    provisioningIp: "10.23.25.102"
manifests/function/baremetal-operator/replacements/networking.yaml:    fieldref: spec.ironic.provisioningIp
