### ISSUE TITLE
Configure K8s API server & Controller Manager settings

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#594]
**Enhancement description**
We want the ability to provide out-of-the-box configuration of the Kubernetes API Server & Controller Manager. This can be performed by updating Cluster Control Plane, Metal3 Machine Template.

See the attached document for the configuration changes. 

**Proposed change**
- Update the Control Plane Metal3 Machine Template to add the additional configurations for both the API Server & Controller Manager as noted in the attachment
- Validate settings applied at deployment time.
[K8 Configuration Settings.txt](https://github.com/airshipit/airshipctl/files/6772160/K8.Configuration.Settings.txt)
7/6 - updated the service-cluster-ip-range for API server & cluster-cidr for Controller Manager based on clarification of requriements.

**Comment by ak3216** [comment]
@pallavgupta has https://review.opendev.org/c/airship/airshipctl/+/797324 in progress. Pallav, please comment so I can assign you.

**Comment by pallavgupta** [comment]
sure, pls assign it to me.

**Comment by pallavgupta** [comment]
https://review.opendev.org/c/airship/airshipctl/+/797324
