### ISSUE TITLE
Spike : Investigate load balancer impacts to support Kubernetes API TLS

### ISSUE THREAD

**Issue by ns5254** [airshipit/airshipctl#596]
**Problem description**
It is unknown if there are any load balancer impacts in supporting TLS v1.2 on Kubernetes API.

**Proposed change**
Determine if load balancer updates are needed to support  TLS v1.2 Kubernetes API.  If impacted, update to support or define necessary implementation stories if larger effort.

**Comment by jezogwza** [comment]
We. can close this, it appears to be. related to the subclusters LB for k8s api.
