### ISSUE TITLE
Upgrade KPT from v0.37.1 to v1.0.0-beta.x

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#598]
**Problem description**
In an effort to keep Airship current with the latest updates of its supporting components, upgrade KPT (Kubernetes Package Toolkit) from v0.37.1 to v1.0.0-beta. In making this upgrade, we will need to ensure that KPT continues to perform component package/component upgrades as well.

Documentation for version >= v1.0 - https://kpt.dev/ < May be blocked if trying to access inside a firewall
Documentation for version <= v0.39 - https://googlecontainertools.github.io/kpt/ 
Release information: https://github.com/GoogleContainerTools/kpt/releases

**Proposed change**
- Identify any major/breaking changes that will come with the upgrade & socialize on the Community Design Call prior to performing the upgrade. 
- After Design Call review, upgrade KPT to v1.0.0-beta.x (beta.1 was released June 22, 2021)
- Make any changes necessary to ensure KPT continues to perform package updates with the move to v1.0.0-beta
- Validate component upgrades performed by KPT are successful

**Comment by matthew-fuller** [comment]
Please assign this to me.

**Comment by ak3216** [comment]
@matthew-fuller done

**Comment by matthew-fuller** [comment]
https://review.opendev.org/c/airship/airshipctl/+/800827

**Comment by matthew-fuller** [comment]
I've been able to successfully update individual packages after converting Kptfiles to the new format, such as `manifests/function/flux/base/upstream/policies`, but the new v1.0-beta doesn't seem to support the notion of a local top-level package that lists dependent upstream packages, so there's no easy way to update everything at once. It requires running something like `kpt pkg update upstream/policies; kpt pkg update upstream/rbac`, etc.

@seaneagan found an [issue](https://github.com/GoogleContainerTools/kpt/issues/467) that seems to be related to this problem. Not sure if there's another way around this issue yet, still investigating...

**Comment by dinesh14nish** [comment]
Matthew, Are you working on this? if not can you please assign it me so i can take it forward from here.

**Comment by dinesh14nish** [comment]
Change made to https://review.opendev.org/c/airship/airshipctl/+/800827

**Comment by dinesh14nish** [comment]
PS https://review.opendev.org/c/airship/airshipctl/+/800827 is merged.
