### ISSUE TITLE
Upgrade CAPD to v1alpha4 for the Docker provider

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#599]
**Problem description (if applicable)**
In an effort to keep Airship current with the latest updates of its supporting components, upgrade CAPD (Cluster-API for Docker provider) to v1alpha4. 

https://github.com/kubernetes-sigs/cluster-api/tree/master/test/infrastructure/docker

As CAPD is bundled in with Cluster API itself, this issue would need to be addressed in conjunction with #518 

**Proposed change**
- Validate CAPD to v1alpha4 with the CAPI v1alpha4 upgrade
- Validate CAPD still functional as the the infra provider for Docker & resolve any breaking changes

**Comment by eratnch** [comment]
Please assign this to me. Thanks.

**Comment by ak3216** [comment]
@eratnch done

**Comment by eratnch** [comment]
PS related to this https://review.opendev.org/c/airship/airshipctl/+/812133 is ready for review.
The other PS  https://review.opendev.org/c/airship/airshipctl/+/811714 is already merged.

**Comment by lb4368** [comment]
@eratnch   Above patchsets are merged.  Can this be closed?

**Comment by eratnch** [comment]
@lb4368 yes, this can be closed.
