### ISSUE TITLE
airshipctl config init subcommand

### ISSUE THREAD

**Issue by jezogwza** [airshipit/airshipctl#6]
This command initializes the configuration with some adequate seed values.

All airshipctl or airshipui behavior is driven by what exists in the configuration files.
We need to create an airship configuration file set to define the intentions the operator/user has for the site.
One goal in Airship 2.0 is to maintain a declarative framework and to help facilitate usage by allowing the operator/user the config init function to seed the configuration.  These configurations will prepare aspect of the configuration such as Manifest/Repository, Bootstrap information  with some default consumed from Treasuremap.
Expectation is that the operator/user will use the config cmd to define its initial target cluster and context intentions for the ephemeral cluster, and the target cluster.

**Comment by drewwalters96** [comment]
[Functionality complete WIP](https://review.opendev.org/707252); will add tests next.

**Comment by drewwalters96** [comment]
Ready for review https://review.opendev.org/707252
