### ISSUE TITLE
Upgrade CAPZ to version v0.5.0 with Cluster API v1alpha4 support

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#600]
**Problem description**
In an effort to keep Airship current with the latest updates of its supporting components, upgrade the CAPZ (Cluster-API for Azure provider) to v0.5.0 with Cluster API v1alpha4 support. The current Azure Provider is v0.4.x supporting Cluster API v1alpha3. 

CAPZ github repo can be found here: https://github.com/kubernetes-sigs/cluster-api-provider-azure

**Proposed change**
- Upgrade CAPZ version to v0.5.0 with Cluster API v1alpha4 support
- Validate CAPZ still functional as the the infra provider for Azure & resolve any breaking changes

**Comment by sshiba** [comment]
Can I be assigned to this issue?

**Comment by sshiba** [comment]
CAPZ supporting CAPI v1alpha4 was supposed to be released last week but a bug was identified and is currently being discussed in Slack [here](https://kubernetes.slack.com/archives/CEX9HENG7/p1625839765424400).

**Comment by ak3216** [comment]
@sshiba, it looks like their github was updated yesterday to reflect the v1alpha4 support & release v0.5.0 of CAPZ. Updated the issue.

**Comment by lb4368** [comment]
Patchsets merged:
https://review.opendev.org/c/airship/airshipctl/+/810039
https://review.opendev.org/c/airship/airshipctl/+/812235
