### ISSUE TITLE
Spike: Use CAPI to upgrade an existing Kubernetes cluster

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#602]
**Problem description**
As part of ongoing operations, we need the ability to perform various component upgrades & understand the behavior of the clusters when these upgrades occur. When it comes to upgrading Kubernetes for an existing cluster, the plan is to use Cluster API to deliver the K8s upgrade to the cluster. 

**Proposed change**
- Test & document the pre-reqs prior to upgrade (i.e. deploying a new image with kubeadm, kubelet & kubectl supporting the new k8s version)
- Test the ability to deliver a a Kubernetes upgrade to an existing cluster via clusterctl. 
- Document & provide findings of the upgrade (e.g. What was the process? What issues were encountered, if any?, etc.)
- Are there any other components that need to be upgraded at the same time (beyond the pre-requisites)?

**Comment by patilsuraj767** [comment]
Please assign this issue to me.
