### ISSUE TITLE
Spike: Upgrade containerd for an existing Kubernetes cluster

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#603]
**Problem description**
As part of ongoing operations, we need the ability to perform various component upgrades & understand the behavior of the clusters when these upgrades occur. When it comes to upgrading containerd for an existing cluster, the plan is to use Cluster API  & Metal 3 to deliver a new image with the upgraded containerd version.

**Proposed change**
- Generate a new image via image-builder with a new version of containerd
- Test the ability to deliver the image to an existing cluster via Cluster API/Metal3.
- Document & provide findings of the upgrade (e.g. What was the process? What issues were encountered, if any?, etc.)
- Are there any other components that need to be upgraded at the same time?

**Comment by pallavgupta** [comment]
pls assign it to me.
