### ISSUE TITLE
Spike: Deliver Ubuntu OS Upgrades for an existing site

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#606]
**Problem description**
As part of ongoing operations, we need the ability to perform various component upgrades & understand the behavior of the site/clusters when these upgrades occur. When it comes to Ubuntu OS upgrades for an existing site, the plan is to use Cluster API & Metal 3 to deliver a new image with the upgrades.

**Proposed change**
- Generate a new image via image-builder with a new Ubuntu OS version
- Test the ability to deliver the image to an existing cluster via Cluster API/Metal3.
- Document & provide findings of the upgrade (e.g. What was the process? What issues were encountered, if any?, etc.)
- Are there any other components that need to be upgraded at the same time?

**Comment by patilsuraj767** [comment]
Please assign this issue to me.
