### ISSUE TITLE
Spike:  CAPI Component Upgrades for Brownfield Sites

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#609]
**Problem description**
Would like to understand the implications of an update to existing CAPI components (Cluster API, Bootstrap Provider, and Control Plane Provider) in a site (brownfield scenario).

https://cluster-api.sigs.k8s.io/tasks/upgrading-cluster-api-versions.html

**Proposed change**
Investigate and document a plan for an upgrade of CAPI components (currently to latest `v1alpha4` version) on an existing cluster.

- Identify dependencies and constraints such as K8s versions, infrastructure provider versions, etc.
- Investigate integration of `clusterctl upgrade` into airshipctl
- Identify impacts to cluster availability and performance during an upgrade

**Comment by SirishaGopigiri** [comment]
Please assign it to me, as I am working on upgrade #518 so I will look at this as well.

**Comment by SirishaGopigiri** [comment]
Related hackmd.io https://hackmd.io/8OXbEcpQTY-P-aoRqFG_WA

**Comment by eak13** [comment]
Closing per above
