### ISSUE TITLE
Spike: Metal3.io Upgrade for Brownfield Site 

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#610]
**Problem description**
Would like to understand the implications of an upgrade to the Metal3.io infrastructure provider in a site (brownfield scenario).  This is related to #609 which addresses upgrade of CAPI components.

**Proposed change**
Investigate and document a plan for an upgrade of the Metal3 CAPI provider (https://github.com/metal3-io/cluster-api-provider-metal3/releases) on an existing cluster.

- Identify dependencies and constraints such as K8s versions, CAPI component versions, baremetal-operator, etc.
- Provide plan for applying upgrade
- Identify impacts to cluster availability and performance during an upgrade

**Comment by shon-phand** [comment]
https://hackmd.io/UT9IKTDLR2u3P06axwuSvA?view

**Comment by lb4368** [comment]
Spike result documented at https://hackmd.io/UT9IKTDLR2u3P06axwuSvA?view     

Closing this.
