### ISSUE TITLE
Spike:  Metal3.io Support for BIOS/Firmware Updates and RAID Configuration Changes

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#614]
**Problem description**
Need to understand how much Metal3.io supports today for BIOS & Firmware upgrades and RAID configuration changes.

**Proposed change**

- Identify current support in Metal3.io for managing BIOS/Firmware upgrades and RAID configuration changes for an existing cluster
- Prepare recommendations for updates in Metal3.io community for support of these upgrades

**Comment by jezogwza** [comment]
Some related issues

- https://github.com/metal3-io/baremetal-operator/issues/206

- https://github.com/metal3-io/baremetal-operator/pull/292

**Comment by sanjib-35** [comment]
Please assign it to me

**Comment by sanjib-35** [comment]
https://hackmd.io/LuE4l1PrTSaUvnOJyfKSsQ?view/

**Comment by SaurabhArora86** [comment]
Hackmd link updated as per design discussion outcomes, this story can be closed now.

[https://hackmd.io/LuE4l1PrTSaUvnOJyfKSsQ?view/](url)
