### ISSUE TITLE
Implement `remoteRef` Configuration Option for Use in Document Pull

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#616]
**Problem description**
For development/debugging purposes it would be useful to be able to specify to check out a gerrit patchset as part of an 'airshipctl document pull' configuration.  There is a `remoteRef` attribute available in the repository checkout section of the airship configuration file that is intended to allow specification of a git reference to be checked out as part of the document pull.  However, this option is currently not implemented.

**Proposed change**
Update the `airshipctl document pull` functionality to checkout the git reference specified in the `remoteRef` configuration option if it is specified.

**Comment by manojkva** [comment]
Please assign this to me. Thanks

**Comment by manojkva** [comment]
Had a discussion with Ruslan Aliev and here are his comments
"that's a complicated issue, talks about supporting remoteRef were started 1.5 years ago and still there is no solution. there are limitations and complication in go-git module, there is need to deep dive into go-git api, gerrit refs and so on, I can't give any clues unfortunately, it requires a complete research, if it were easy this functionality would have been implemented long ago" 

I think this will need a design discussion and would need research.
