### ISSUE TITLE
Standardize airshipctl YAML documents as .yaml extension

### ISSUE THREAD

**Issue by alexander-hughes** [airshipit/airshipctl#62]
**Problem description (if applicable)**
Currently Ansible documents (playbooks, roles, tasks, etc.) are mixed extensions of .yml and .yaml

**Proposed change**
Rename all .yml files to .yaml, and update their references in code base to .yaml

**Potential impacts**
None

**Comment by sirajyasin** [comment]
I can start on this if no one has picked it yet.

**Comment by ianpittwood** [comment]
Merged in this change https://review.opendev.org/#/c/709539/
