### ISSUE TITLE
AIAP: Switch to a readiness probe for the docker and libvirt containers

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#629]
**Problem description (if applicable)**
The `artifact-setup` and `infra-builder` containers are using a naive approach of simply sleeping for 30 seconds, with the expectation that the libvirt and docker services will become available in that time before they begin execution:
* https://github.com/airshipit/airshipctl/blob/362cc4b88039deaba5b43ae3fdef091d3c067255/tools/airship-in-a-pod/artifact-setup/assets/entrypoint.sh#L38-L39
*  https://github.com/airshipit/airshipctl/blob/362cc4b88039deaba5b43ae3fdef091d3c067255/tools/airship-in-a-pod/infra-builder/assets/entrypoint.sh#L17-L18

**Proposed change**
Modify the base AIAP PodSpec to use [readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) so the above containers can be sure the services are available. This will prevent errors in the case where the services take a long time to come up while also providing a potential speed boost when they come up very quickly.

**Comment by ian-howell** [comment]
After thinking about this for a minute, a readiness probe may not be the exact mechanism for this task. However, it would still be nice to have a more intelligent waiting mechanism than `sleep`

**Comment by sirajyasin** [comment]
I can start working on this issue.

**Comment by sreejithpunnapuzha** [comment]
@sirajyasin all yours
