### ISSUE TITLE
Implement `airshipctl version`

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#630]
**Problem description (if applicable)**
`airshipctl version` currently reports that it is v0.1.0, no matter when or how the binary was created.

**Proposed change**
Borrow from a more mature project such as [helm](https://github.com/helm/helm/blob/main/Makefile#L34-L68) or [kustomize](https://github.com/kubernetes-sigs/kustomize/blob/2bfc7cc1b0bf0afb7b87594c8be48b6d17454923/api/provenance/provenance.go) so that we can display the tag or git sha of the built binary.

**Comment by ian-howell** [comment]
Here's what I was talking about with linker flags on the Flight Plan call: https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications

**Comment by sreejithpunnapuzha** [comment]
Commit https://review.opendev.org/c/airship/airshipctl/+/810128 Pushed with the changes.

**Comment by sreejithpunnapuzha** [comment]
Commit https://review.opendev.org/c/airship/airshipctl/+/810128 is merged. hence closing this issue.
