### ISSUE TITLE
AIAP: Allow pulling a private airshipctl binary repo

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#632]
**Problem description (if applicable)**
We can pull airship manifests from a private repo, but that functionality doesn't currently exist for the binary repo itself. 

**Proposed change**
Modify the `artifact-setup` container to implement authorization so that we can pull an airshipctl binary from a private repository

**Comment by sirajyasin** [comment]
I can start working on this issue. Can someone assign this issue to me ?

**Comment by sreejithpunnapuzha** [comment]
@sirajyasin all yours

**Comment by sirajyasin** [comment]
PS https://review.opendev.org/c/airship/airshipctl/+/809290 in review

**Comment by sirajyasin** [comment]
The related PS https://review.opendev.org/c/airship/airshipctl/+/809290 is merged. This issue can be marked completed

**Comment by eak13** [comment]
Closing per code merge
