### ISSUE TITLE
Allow to specify poll interval for k8s apply phases

### ISSUE THREAD

**Issue by raliev12** [airshipit/airshipctl#633]
**Problem description (if applicable)**
Currently it's not possible to specify poll interval - how often we should poll for the status of resources. By default, it's 2 seconds - it could create excessive load on k8s cluster and we should have a possibility to tune this interval (it's allowed in cli utils API). 

**Proposed change**
Add `PollInterval`  property to k8s_applier executor.

**Potential impacts**
None.

**Comment by raliev12** [comment]
Please assign this issue to me. Related PS is here - https://review.opendev.org/c/airship/airshipctl/+/808528

**Comment by raliev12** [comment]
Can be closed since PS https://review.opendev.org/c/airship/airshipctl/+/808528 was successfully merged.

**Comment by eak13** [comment]
Closing per merge
