### ISSUE TITLE
AIAP: Passwords and tokens are stored as plaintext

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#636]
**Describe the bug**
When providing a password or personal access token to AIAP, the value is used as an environment variable, meaning that it is easily accessible via a `kubectl describe` of the pod

**Steps To Reproduce**
Deploy an instance of AIAP with a specified password.

**Expected behavior**
Passwords should not be visibile

**Comment by sirajyasin** [comment]
This PS (https://review.opendev.org/c/airship/airshipctl/+/809290) will address this issue.

**Comment by sirajyasin** [comment]
The related PS https://review.opendev.org/c/airship/airshipctl/+/809290 is merged. This issue can be marked completed

**Comment by eak13** [comment]
Closing per above.
