### ISSUE TITLE
Uplift K8s Docker provider to v1.21

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#638]
As part of the general k8s uplift outlined in #589, uplift the Docker provider to v1.21 as well.

**Comment by eak13** [comment]
From @rkjain: The patch set to uplift docker version to 1.21 is here - https://review.opendev.org/c/airship/airshipctl/+/795582
Please comment and I'll assign you. Thanks.

**Comment by rkjain** [comment]
Hi, Please assign this to me. @eak13  Thank you

**Comment by rkjain** [comment]
The patch set https://review.opendev.org/c/airship/airshipctl/+/81078, includes changes to update k8s version from 1.18.6 to 1.21.2. As a result I have abandoned the patch set https://review.opendev.org/c/airship/airshipctl/+/795582 I had shared earlier.

**Comment by rkjain** [comment]
This patchset can be closed. The work for this ps overlaps with changes done by snehal for capdv1alpha4 (k8s v1.21)work (https://github.com/airshipit/airshipctl/issues/647). This patchet focused on changing the cluster templates for v1alpha3 and k8sv1.21. Now, that the cluster templates have already moved to v1alpha4, this work is not required.

**Comment by lb4368** [comment]
Closing per above.  Issue covered in #599 and #647.
