### ISSUE TITLE
First Target Node BMH Image HREF Should Not Reference Ephemeral Host

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#641]
**Problem description**
During initial deployment of a target cluster, the first control plane node is provisioned from the ephemeral cluster.  Therefore, the BMH resource for this node references an image href endpoint on the ephemeral host.  Since the ephemeral host is removed, this causes issues in certain scenarios like a Day 2 BMO upgrade (#610) when the BMH resources are validated causing the node to go into a deprovisioning state.

**Proposed change**
Identify a solution to correct the initial target cluster node image href to reference a valid target cluster endpoint.

- Could something be added to the clusterctl move phase to correct?
- Could something be done after control plane expansion?
- Need to care for any impacts due to updating the BMH image endpoint

**Comment by joshuaherrera** [comment]
Hi, I can take this issue.
