### ISSUE TITLE
Fix Broken Links in Airshipctl Docs

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#644]
**Describe the bug**
The docs broken link finder has identified the following broken links in airshipctl documentation.  Review and update documentation as needed to resolve. 

airshipctl\CONTRIBUTING.md
FAIL: https://doc.airshipit.org/airshipctl/developers.html
airshipctl\docs\source\phases.rst
FAIL: https://godoc.org/opendev.org/airship/airshipctl/pkg/clusterctl/client#ClusterctlExecutor
FAIL: https://10.23.25.102:6443
FAIL: https://10.23.25.101:6443
FAIL: https://godoc.org/opendev.org/airship/airshipctl/pkg/clusterctl/client#ClusterctlExecutor
airshipctl\docs\source\plugins.md
airshipctl\docs\source\providers\cluster_api_azure.md
FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_docker.md
FAIL: https://review.opendev.org/airship/airshipctl
FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_gcp.md
FAIL: https://review.opendev.org/airship/airshipctl
airshipctl\docs\source\providers\cluster_api_openstack.md
FAIL: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/docs/env.rc
FAIL: http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.5-server-amd64.iso
FAIL: http://10.0.4.4/identity
airshipctl\docs\source\secrets-guidelines.md
FAIL: https://github.com/GoogleContainerTools/kpt-functions-catalog/tree/master/examples/contrib/sops
airshipctl\docs\source\virtual_redfish_bmc.md
FAIL: https://github.com/dell-esg/tool-pkgs/blob/master/Redfish_tools.zip
FAIL: http://192.168.122.10:8000/redfish/v1/Systems
FAIL: http://192.168.122.10:8000/redfish/v1/Systems/8e5b2dc4-0c1d-4509-af2f-7a4a8f2121a8
airshipctl\manifests\function\cni\tigera-operator\README.rst
FAIL: https://github.com/airshipit/airshipctl/tree/master/manifests/function/tigera-operator/v1.15.0/custom-resources.yaml

**Comment by vetbijaya** [comment]
I can work on this one. I already started working to fix for Openstack provider: https://review.opendev.org/c/airship/airshipctl/+/810452

**Comment by mf4716** [comment]
Thanks @vetbijaya (Bijaya) for picking this one up.

**Comment by vetbijaya** [comment]
Looks like Airshipbot isn't working properly. Related PS: https://review.opendev.org/c/airship/airshipctl/+/811218
