### ISSUE TITLE
AiaP - Develop a method to support caching on a remote node

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#645]
**Proposed change**
Airship in a Pod provides the ability for users to cache items like binaries, ISO images, manifests, etc. This allows users to skip time consuming steps like having to build the image each time AiaP is run.

The current mechanism only supports caching within the current node where AiaP is running. AiaP needs the ability to support caching outside of the local node so cached files are accessible on a remote node .

**Comment by wahlstedtw** [comment]
Patchset was merged to solve this issue: https://review.opendev.org/c/airship/airshipctl/+/820580

**Comment by eak13** [comment]
Thanks. we can close this one out
