### ISSUE TITLE
Update Docker Provider to CAPI v0.4.2 and the lastest clusterctl image

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#647]
**Problem description (if applicable)**
Since #642, the Docker provider uses an older clusterctl image and CAPI version. The Docker provider should be updated as soon as possible to match CAPI v0.4.2 when https://review.opendev.org/c/airship/airshipctl/+/802025 merges.

**Comment by rkjain** [comment]
Please assign this to me

**Comment by rkjain** [comment]
I see snehal has already created a patchset for this issue. https://review.opendev.org/c/airship/airshipctl/+/811714 
She can comment here, and get it assigned to her

**Comment by eak13** [comment]
Patchset https://review.opendev.org/c/airship/airshipctl/+/811714 has merged.

**Comment by lb4368** [comment]
Reopening awaiting merge of PS https://review.opendev.org/c/airship/airshipctl/+/812133
