### ISSUE TITLE
AIAP: Create a multi-node `infra-builder` image

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#652]
**Problem description (if applicable)**
The default `infra-builder` image in AIAP uses 1 control plane node and 1 worker node. We would like to have an additional image which creates 3 control planes and 2 workers.

This issue will likely go hand-in-hand with #648 and #651

**Comment by pallavgupta** [comment]
@eak13 pls assign this issue to me. Thanks.

**Comment by pallavgupta** [comment]
https://review.opendev.org/c/airship/airshipctl/+/816844
