### ISSUE TITLE
AIAP: support non test GPG keys

### ISSUE THREAD

**Issue by jgu17** [airshipit/airshipctl#654]
**Problem description (if applicable)**

AIAP can only deploy using the Mozilla SOPS gpg key for testing purpose.

**Proposed change**
Add support in AIAP to use a production gpg key for secret encryption and decryption.

**Potential impacts**
Potential security or performance related impacts.

**Comment by sirajyasin** [comment]
This Issue can be marked completed/Closed. Both the related PSs are merged now.

**Comment by eak13** [comment]
closing per merge
