### ISSUE TITLE
Enable extraction of target/workload cluster artifacts

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#658]
As a prerequisite to decommissioning the existing script-based airshipctl gates and moving to use AiaP, we need to enable the extraction of target/workload cluster artifacts (logs etc).  

Suggested approach is to reuse the existing gate scripting that does this, perhaps extracting the kubeconfig out of the runner container (if that can be made to work), or running the collector script inside the runner container and pulling the results out.

**Comment by aodinokov** [comment]
@eak13 , @michael-beaver 
a little comment to this:
>As a prerequisite to decommissioning the existing script-based airshipctl gates and moving to use AiaP

if I remember correctly our discussion on PTG we decided to PREPARE for that, but don't disable the script based approach until AIAP will be comfortable to work with by developers.
So it's ok to improve AIAP jobs, but please don't touch the legacy job :)
This is just to make sure that we won't turn them off based on the description of that task :)

cc: @mattmceuen
