### ISSUE TITLE
AIAP: Documentation redirect

### ISSUE THREAD

**Issue by eak13** [airshipit/airshipctl#660]
We need to change the documentation so the removed AIAP link in docs redirects to the new link. This will satisfy Bing’s cached #1 search result & ensure the correct documentation appears.

**Comment by gedrivera** [comment]
Can no longer replicate the issue. After redundant readme was removed, links are now pointing to the correct AIAP documentation as first result. Correct link is now showing as Bing #1 search result, and have cross-referenced with other browsers as well. This story can be closed out.

**Comment by eak13** [comment]
Closing per above.
