### ISSUE TITLE
source|target version replacement for qcow_bundle is missing. 

### ISSUE THREAD

**Issue by patilsuraj767** [airshipit/airshipctl#661]
**Describe the bug**
In [ironic-deployment-versions-replacements](https://github.com/airshipit/airshipctl/blob/master/manifests/function/ironic-deployment/v0.5.0/replacements/versions.yaml) source|target replacement for qcow_bundle is missing because of which qcow_bundle  version mentioned in `airshipctl-base-catalogues/versions-airshipctl.yaml` is not reflecting  in capm3-ironic deployment template.

**Comment by lb4368** [comment]
@patilsuraj767   Since patchset is merged can this be closed?

**Comment by eak13** [comment]
Closing per patchset merge
