### ISSUE TITLE
Move document labeling code from initinfra to the document pkg

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#71]
**Problem description (if applicable)**
The initinfra implementation includes logic to label every document.  Moving this code elsewhere will make it reusable elsewhere in airshipctl.

From #11 in a comment by @alanmeadows: 

> I'd also advocate that for instance, https://review.opendev.org/#/c/693238/21/pkg/cluster/initinfra/infra.go L84 another example that would benefit from centralization in the Bundle itself. 

**Proposed change**
Move the logic that labels documents with initinfra labels to the document package.

**Potential impacts**
No potential security or performance related impacts anticipated.

**Comment by sirajyasin** [comment]
I can pick this if no one has already started working

**Comment by ianpittwood** [comment]
All yours @sirajyasin

**Comment by sirajyasin** [comment]
I see that the clean up is already taken care with the dependent issues #102 and #103 . Please help me understand if there is any pending work on this issue.

**Comment by sirajyasin** [comment]
This issue can be marked closed as the cleanup is addressed in the dependent issues #102 #103

**Comment by drewwalters96** [comment]
Thanks @sirajyasin
