### ISSUE TITLE
NB API -- Validate and Compare Expected Hardware Configuration for BMH 

### ISSUE THREAD

**Issue by pramchan** [airshipit/airshipctl#76]
**Problem description (if applicable)**
This is a feature carried over from JIRA AIR-79-- Validate and Compare Expected Hardware Configuration for BM hosts.  This feature will use AirshipCTL documents from  interface to select , compare and label  the BM host using BM Operator. 

Refer metal3.io  -- https://github.com/metal3-io/metal3-docs/pull/60 

**Proposed change**
- No change to existing story

**Potential impacts**
- Unknown

**Comment by ianpittwood** [comment]
@pramchan could you please edit the proposed change section to describe the proposed way of resolving this story?

**Comment by jezogwza** [comment]
Duplicated #77
