### ISSUE TITLE
Document for deploying HCC CRD

### ISSUE THREAD

**Issue by digambar15** [airshipit/airshipctl#79]
**Problem description (if applicable)**
Document for deploying tge CRD and controller of HardwareClassificationController needs to be defined.
It should comply with the rest of the components that are considered Infrastructure.
See https://review.opendev.org/#/c/706533/ for examples.
This ensures that it will be inline with the needs that would allow cluster initinfra to deploy this component when appropriate.

**Proposed change**
Will have to add below files to airshipctl -
manifests/global/crd/hardware-classification-controller/hardwareclassificationcontroller.metal3.io.yaml
manifests/global/crd/hardware-classification-controller/kustomization.yaml

**Potential impacts**
None

**Comment by sharajat** [comment]
@ian-howell 
https://review.opendev.org/#/c/738410/
Kindly review

**Comment by mattmceuen** [comment]
I think this one can probably be closed with Rajat's change above.  I think we should do follow-on work to get some production-grade hardware profiles added to Treasuremap, and integrated with a CICD-oriented site definition.

**Comment by lb4368** [comment]
Closing this.  New HCC features are taken care in #455.
