### ISSUE TITLE
metal3-io RAID and BIOS Spec

### ISSUE THREAD

**Issue by demonCoder95** [airshipit/airshipctl#84]
**Problem description (if applicable)**
This maps to AIR-90 story on Airship Jira.
https://airship.atlassian.net/browse/AIR-90

Submit a spec to the metal3-io documents repository with a proposed spec on how you will declaratively define how the RAID and BIOS will be tested

**Proposed change**
Specifications submitted into metal3-io BMO that describe the BIOS extension to the spec
Relates-to: https://github.com/metal3-io/metal3-docs/pull/63

The RAID spec is already in the pipeline, in metal3-io upstream
Relates-to: https://github.com/metal3-io/baremetal-operator/pull/292

The issue is to track progress on the work upstream in metal3-io community.
**Potential impacts**
None so far.

**Comment by demonCoder95** [comment]
The BIOS spec work I'm doing myself. The RAID spec work, collaborating with Fujitsu team since they already have the work in pipeline close to merging.

**Comment by ian-howell** [comment]
@demonCoder95 have you made any progress on this issue?

**Comment by demonCoder95** [comment]
Yes, there's been a lot of progress. 

The metal3-docs spec PR #63 that is referenced was merged a couple or so weeks ago. Also, the development work on RAID configuration is going well, and should have some functionality very soon.
 I've started working on implementation of BIOS configuration as well, after the spec was merged.

**Comment by demonCoder95** [comment]
We're waiting for the RAID spec to be merged, then this issue can be closed. I'll open another issue that tracks AIR-91, which is the implementation of RAID and BIOS.

**Comment by demonCoder95** [comment]
RAID and BIOS specifications have been merged into metal3 BMO and the development work is almost complete, testing in progress. 

@ak3216 This issue can be closed, and I'll open a new one that will track the status of the dev work to be finished and ready for airship usage.

**Comment by ak3216** [comment]
Closing per the above comment & new issue referenced in #499
