### ISSUE TITLE
Unable to get cluster resources details using "airshipctl kubectl" CLI 

### ISSUE THREAD

**Issue by vkdrao4git** [airshipit/airshipctl#87]
**Describe the bug**

I have a working kubeconfig file using which i am able to interact with the remote cluster without any issue as shown below 
root# export KUBECONFIG=~/.airship/kubeconfig
root# kubectl get ns
NAME                           STATUS   AGE
aqua-network-policy-sonobuoy   Active   20d
ceph                           Active   21d
default                        Active   21d
gstools-deploy                 Active   20d
heptio-sonobuoy                Active   20d
kube-node-lease                Active   21d
kube-public                    Active   21d
kube-system                    Active   21d
openstack                      Active   20d
osh-infra                      Active   20d
tenant-ceph                    Active   20d
ucp                            Active   21d
utility                        Active   20d
root#

However when i tried to interact with the same remote cluster using airshipctl's kubectl interface , it is failing with the error as show below (Just giving the whole sequence of steps) 

root# export KUBECONFIG=~/.airship/kubeconfig
root# kubectl get ns
NAME                           STATUS   AGE
aqua-network-policy-sonobuoy   Active   20d
ceph                           Active   21d
default                        Active   21d
gstools-deploy                 Active   20d
heptio-sonobuoy                Active   20d
kube-node-lease                Active   21d
kube-public                    Active   21d
kube-system                    Active   21d
openstack                      Active   20d
osh-infra                      Active   20d
tenant-ceph                    Active   20d
ucp                            Active   21d
utility                        Active   20d
root# unset KUBECONFIG
root# kubectl get ns
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root# airshipctl kubectl get ns  =>  I am expecting this one should work as airshipctl should pick the config from the default path (~/.airship) , in which i have the correct configs in place 
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root#

I believe the airship config is good . Please correct me if i am working. 

I am trying to test the integration of airshipctl with kubectl. 
 
Contents of airship config file 
===================

root# cat ~/.airship/config
apiVersion: airshipit.org/v1alpha1
clusters:
  kubernetes:
    cluster-type:
      target:
        bootstrap-info: ""
        cluster-kubeconf: kubernetes_target
contexts:
  admin@kubernetes:
    context-kubeconf: kubernetes_target
current-context: admin@kubernetes
kind: Config
manifests:
  default:
    repository:
      checkout:
        branch: master
        commit-hash: master
        force: false
        remote-ref: master
        tag: ""
      url: https://opendev.org/airship/treasuremap
    target-path: /tmp/default
modules-config:
  bootstrapInfo:
    default:
      builder:
        networkConfigFileName: network-config
        outputMetadataFileName: output-metadata.yaml
        userDataFileName: user-data
      container:
        containerRuntime: docker
        image: quay.io/airshipit/isogen:latest
        volume: /srv/iso:/config
      remoteDirect:
        isoUrl: http://localhost:8099/debian-custom.iso
        remoteType: redfish
users:
  admin: {}
root#

Contents of  the kube config file 
===================
root# cat ~/.airship/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: cluster-ca.pem
    server: https://127.0.0.1:9090
  name: kubernetes_target
contexts:
- context:
    cluster: kubernetes_target
    user: admin
  name: admin@kubernetes
current-context: admin@kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: admin.pem
    client-key: admin-key.pem
root#

Output airshipctl config commands
=======================

root# airshipctl config get-context
Context: kubernetes
context-kubeconf: kubernetes_target

LocationOfOrigin: /root/.airship/kubeconfig
cluster: kubernetes_target
user: admin

root# airshipctl config get-cluster
Cluster: kubernetes
target:
bootstrap-info: ""
cluster-kubeconf: kubernetes_target

LocationOfOrigin: /root/.airship/kubeconfig
certificate-authority: cluster-ca.pem
server: https://127.0.0.1:9090

root# airshipctl config get-credentials
LocationOfOrigin: /root/.airship/kubeconfig
client-certificate: admin.pem
client-key: admin-key.pem
root#

Please note i have a ssh tunnel on my local host to the remote cluster ep. 

**Steps To Reproduce**

1. Clone the airshipctl repo from git 

2. make build 

3. Initialize the airship configurations using "airshipctl config init"  , which generates the config and kubeconfig files in ~/.airship/ 

4. update the kubeconfig file with the remote cluster details and have the certs for remote cluster in  in place on the local host. 

5. Run the command "airshipctl kubectl get ns" 

**Expected behavior**

As airshipctl providing an interface to kubectl  cli , i expect the kubectl commands should work as expected through this interface as airshipctl looks for the configs in the default path , which is ~/.airship

**Environment**
- airshipctl Version:

root# airshipctl version
airshipctl:   v0.1.0
root#
- Operating System:
root# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
root#
- Kernel version:

root# uname -a
Linux ubuntuvm 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root#
- Kubernetes Version:

root# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Go version:
root# go version
go version go1.13 linux/amd64
root#
- Hardware specs (e.g. 4 vCPUs, 16GB RAM, bare metal vs VM):

**Comment by alexander-hughes** [comment]
airshipctl kubectl subcommand is being removed [here](https://review.opendev.org/#/c/710085/)

**Comment by vkdrao4git** [comment]
@alexander-hughes thanks for the confirmation.
