### ISSUE TITLE
Definition of ArmadaChart CRD

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#92]
**Problem description (if applicable)**
In Airship 1.0, ArmadaChart document carried below data and is stored in Deckhand for Armada to consume when it is invoked to deploy / upgrade the chart.
(a) chart metadata (namespace, labels, wait time, source URL of the helm chart, protected flag etc.)
(b) Value overrides
Given that Deckhand is replaced by Kustomize and general guideline, most of the yaml artifacts are evaluated for their conversion to CRD, ArmadaChart document in Airship 1.0 needs to be evaluated for its coversion to CRD or in some other form (chart metadata in Argo workflow and value overrides as plain yaml file).

**Proposed change**
ArmadaChart CRD needs to defined so that data in Armada chart document in Airship 1.0 is recorded in the corresponding ArmadaChart CR for each chart. 
- ArmadaChart CR is expected to be created on target cluster, before Armada can deploy / upgrade Helm chart on target cluster.
- Armada would retrieve the CR from target K8s cluster and use the informantion in deployment of corresponding Helm chart.
- if values overrides include secure data then the secure data should be stored as secret and secret should be referenced in the ArmadaChart CR. It should be ensured that it is possible to do so.

**Potential impacts**
It would enable availability of chart metadata and value overrides for Armada while deploying the corresponding helm chart.

**Comment by drewwalters96** [comment]
This issue may be a better fit for github.com/airshipit/armada.

It's currently a WIP https://review.opendev.org/#/c/706967/12/manifests/chart-crd.yaml

**Comment by sb1975** [comment]
So regarding this statement - "Armada would retrieve the CR from target K8s cluster and use the informantion in deployment of corresponding Helm chart "
Are we planning for using Armada controller(last I recall not) or basically the Armada CR would be observed and target state ensured by the argo-controller ?

**Comment by seaneagan** [comment]
This was implemented here: https://review.opendev.org/#/c/697728/
