### ISSUE TITLE
Leverage Armada to apply Chart from Argo workflow

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#93]
**Problem description (if applicable)**
As per Airship 2.0 architecture, Argo workflows will executed to deploy software components for platform services (OpenStack, LMA Stack). Argo workflows are going to leverage one instance of ArmadaCLI to apply one and only one helm chart, as a leaf level step in multiple layers of workflowTemplates structured in form of a tree. Armada's python version in Airship 1.0 needs to be enhanced to fit it into flows of Airship 2.0.

**Proposed change**
Python based Armada as is in Airship 1.0 needs be enhancement for it to fit it into Airship 2.0 flow.
- to have entrypoint "apply_chart" in its CLI interface to apply a single chart as opposed to an entire manifest. This allows chart deployment ability of Armada to be used with third party Argo workflow implementations for deploying multiple charts. 
- to be able to consume the chart metadata and value override from "ArmadaChart" CR.
- to be able to retrieve the secure data from secrets, which will be referenced in "ArmadaChart" CR for a given chart.
- to ensure idempotency of workflow execution at each layer.

**Potential impacts**
These enhancements would enable python based Armada as used in Airship 1.0 to deploy the software components for platform services in the order, depicted in Argo workflow, with smaller effort than developing Armada operator to process ArmadaChart CRs.

**Comment by drewwalters96** [comment]
This issue appears to only contain work that needs to be completed in https://github.com/airhsipit/armada. This should probably filed over there.

This is also a WIP: https://review.opendev.org/#/c/697728/
