### ISSUE TITLE
Cleanup of old executions of Argo workflows and storage of workflow logs

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#98]
**Problem description (if applicable)**
airshipctl shall allow cleanup of previously executed Argo workflows and allow storing the workflow logs at remote storage.

**Proposed change**
The Airshipctl driven workflows will be ephemeral. Airshipctl will deliver them each time as a new instance. Older completed workflows will remain in the target cluster only for informational purposes and can or will be removed eventually by the AutoCleanup functionality .

Argo supports retrieving the logs from workflows, but it also supports archiving them to an artifact repository, such as s3. Argo shall be deployed with a storage mechanism (such as minio https://github.com/minio/minio), to enable workflow to store an object / log file for every run, before the workflows are cleaned up from target cluster.

**Potential impacts**
Ability to clean up previous runs of workflows would keep the view of workflows clean for user.

**Comment by drewwalters96** [comment]
This was superceded by #177. Closing unless we need this.
